-- The Live Shop — Copyright (c) 2026 Serhii Merenkov / Technologies LLC
-- Licensed under the OwnNet Source License 1.1 (source-available). See LICENSE.
-- Commercial use requires a separate agreement: mer.sergei@gmail.com

-- 067_pos_demo_suncity.sql — GENERATED by scripts/demo-suncity/gen-migration.mjs
-- from scripts/demo-suncity/menu.json and techcards.mjs. Edit those and re-run
-- the generator; `pos.demo-suncity.test.ts` runs it with --check and fails on
-- a stale file. TechDocs/POS_DEMO_SUNCITY.md is the design and resume point.
--
-- «Sun City» (Малин) — sushi, pizza and fast food for delivery, a café without
-- tables: the real menu of https://suncitymalyn.com.ua/ as of 2026-10-07
-- (264 dishes in 15 categories, the site's own photos under
-- public/demo-suncity/). A pizza is one card in two sizes, and its crust costs
-- more on the bigger one — the answer's `label_deltas` (migration 066).
--
-- ⚠ READ BEFORE DEPLOYING. Like 039/048/053, this inserts DEMO DATA into every
-- database the runner touches — production included — with PUBLICLY KNOWN
-- credentials (owner@suncity.shop / owner123, owner PIN 0000, seller PIN
-- 1234). Those accounts see only their own store. Dropping it takes the
-- ordered delete of 048's header, with the bill tables first as in 053.
--
-- Idempotency is the 039 stamp (`pos_demo_seed`, compared with `v_version`):
-- no store → build; stamp = v_version → return; older or absent → rebuild the
-- catalogue (its sales, documents and carts go with it) keeping the store row,
-- its configuration and staff. The generator's VERSION is `v_version`.
-- Never written here: `module_remotes` (a deployment choice the super admin
-- makes) and anything the owner may have set on the store row since — the
-- public-menu token and the profile are filled only while still empty.

DO $$
DECLARE
  -- Bump in the generator when the catalogue changes. The header says what that does.
  v_version CONSTANT int := 1;
  v_stamped  int;
  v_store    bigint;
  v_owner    bigint;
  v_prod     bigint;
  v_variant  bigint;
  v_part     bigint;
  v_group    bigint;
  v_rows     int;
  r          record;
  c          record;
BEGIN
  SELECT id INTO v_store FROM pos_stores WHERE slug = 'demo-suncity';
  SELECT version INTO v_stamped FROM pos_demo_seed WHERE slug = 'demo-suncity';

  IF v_store IS NOT NULL AND v_stamped = v_version THEN
    RAISE NOTICE 'demo-suncity already at version % — skipping', v_version;
    RETURN;
  END IF;

  IF v_store IS NOT NULL THEN
    RAISE NOTICE 'demo-suncity at version % — rebuilding its catalogue at %',
      COALESCE(v_stamped::text, 'none'), v_version;

    -- Content only; the store row and its configuration stay. 053's order:
    -- the bill tables first (a store without the `tables` module has none,
    -- but a visitor with the demo's credentials could have opened one).
    DELETE FROM pos_bill_item_components WHERE store_id = v_store;
    DELETE FROM pos_bill_items WHERE store_id = v_store;
    DELETE FROM pos_bill_rounds WHERE store_id = v_store;
    DELETE FROM pos_bills WHERE store_id = v_store;
    DELETE FROM pos_fiscal_receipts WHERE store_id = v_store;
    DELETE FROM pos_refund_items
     WHERE refund_id IN (SELECT id FROM pos_refunds WHERE store_id = v_store);
    DELETE FROM pos_refunds WHERE store_id = v_store;
    DELETE FROM pos_payments WHERE store_id = v_store;
    DELETE FROM pos_sale_item_modifiers WHERE store_id = v_store;
    DELETE FROM pos_sale_item_components WHERE store_id = v_store;
    DELETE FROM pos_sale_items WHERE store_id = v_store;
    DELETE FROM pos_sales WHERE store_id = v_store;
    DELETE FROM pos_idempotency_keys WHERE store_id = v_store;
    DELETE FROM pos_stock_reservations WHERE store_id = v_store;
    DELETE FROM pos_parked_cart_items WHERE store_id = v_store;
    DELETE FROM pos_parked_carts WHERE store_id = v_store;
    DELETE FROM pos_preorder_items WHERE store_id = v_store;
    DELETE FROM pos_preorders WHERE store_id = v_store;
    DELETE FROM pos_stock_document_lines WHERE store_id = v_store;
    DELETE FROM pos_stock_documents WHERE store_id = v_store;
    DELETE FROM pos_product_modifier_groups WHERE store_id = v_store;
    DELETE FROM pos_modifiers WHERE store_id = v_store;
    DELETE FROM pos_modifier_groups WHERE store_id = v_store;
    DELETE FROM pos_product_components WHERE store_id = v_store;
    DELETE FROM pos_variant_barcode_fixes WHERE store_id = v_store;
    DELETE FROM pos_stock_movements WHERE store_id = v_store;
    DELETE FROM pos_stock WHERE store_id = v_store;
    DELETE FROM pos_product_tags
     WHERE product_id IN (SELECT id FROM pos_products WHERE store_id = v_store);
    DELETE FROM pos_variants WHERE store_id = v_store;
    DELETE FROM pos_products WHERE store_id = v_store;
    DELETE FROM pos_tags WHERE store_id = v_store;

    SELECT id INTO v_owner
      FROM pos_staff
     WHERE store_id = v_store AND role = 'owner' AND is_active
     ORDER BY id LIMIT 1;
  ELSE
    INSERT INTO pos_stores (name, slug, currency, timezone, vertical)
    VALUES ('Sun City', 'demo-suncity', 'UAH', 'Europe/Kyiv', 'cafe')
    RETURNING id INTO v_store;
  END IF;

  -- The bcrypt(10) digests 039 introduced (owner123 / 0000 / 1234). Only when
  -- the store has nobody: a rebuild never rewrites anyone's credentials.
  IF v_owner IS NULL THEN
    INSERT INTO pos_staff (store_id, role, display_name, login, password_hash, pin_hash)
    VALUES (
      v_store, 'owner', 'Власник', 'owner@suncity.shop',
      '$2b$10$SAR9nrA9Y5gEsMs0MJuRbOwC7CySrhVz7uBQzLwgUulAkMLLfzNmG',
      '$2b$10$z0Fo3/EBQ0JxfO9NCJG65uT6kLeMT2gceRpiSlAokkSv0Bru9R5Bq'
    )
    RETURNING id INTO v_owner;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pos_staff WHERE store_id = v_store AND role = 'seller' AND is_active
  ) THEN
    INSERT INTO pos_staff (store_id, role, display_name, pin_hash)
    VALUES (
      v_store, 'seller', 'Касир',
      '$2b$10$4vDSYZFiSOgarz.z0sihVeqbYlAtUG0ZfI1uNFbWDGhzi4jKVaG1q'
    );
  END IF;

  -- ── Categories ──────────────────────────────────────────────────────────
  -- The site's own, in its order, each a tab on the till's bar. All cooked
  -- in one kitchen, so every one routes the ticket there.
  INSERT INTO pos_tags (store_id, name, sort_order, color, show_in_catalog_bar, station)
  SELECT v_store, t.name, t.ord, t.color, TRUE, 'kitchen'
  FROM (VALUES
      ('Суші пончик', 10, 'rose'),
      ('Українські роли', 20, 'green'),
      ('Роли', 30, 'rose'),
      ('Сети', 40, 'purple'),
      ('Піцца', 50, 'orange'),
      ('Меню', 60, 'blue'),
      ('ВОК', 70, 'amber'),
      ('Гриль', 80, 'orange'),
      ('Бургери', 90, 'amber'),
      ('Шаурма', 100, 'amber'),
      ('Хот-Дог', 110, 'amber'),
      ('Темпура', 120, 'rose'),
      ('Фаст-Фуд', 130, 'teal'),
      ('Пропозиція тижня', 140, 'green'),
      ('Салати', 150, 'green')
  ) AS t(name, ord, color);

  -- ── Dishes ──────────────────────────────────────────────────────────────
  -- The description is the weight the site gives; the composition is the
  -- site's text, verbatim. Allergens stay empty: empty means «not said», and
  -- nobody here may say it for a real kitchen. A dish with a tech card is a
  -- `derived` recipe; every other one has its own shelf.
  FOR r IN
    SELECT * FROM (VALUES
      ('РОЛ ІНЬ ЯНЬ', '/demo-suncity/rol-in-ian.jpg', '220 г', NULL, 'simple', 'own'),
      ('ЧОРНИЙ ДРАКОН', '/demo-suncity/chornyi-drakon.jpg', '220 г', 'Рис, сир філадельфія, огірок, лосось, вугор, кунжут, тобіко', 'simple', 'own'),
      ('РОЛ BLACK FIRE', '/demo-suncity/rol-black-fire.jpg', '220 г', 'Рис, сир Філадельфія, лосось, кунжут, авокадо, огірок', 'simple', 'own'),
      ('КАЛІФОРНІЯ ЛОСОСЬ', '/demo-suncity/kaliforniia-losos.jpg', '220 г', 'Лосось,огірок,вершковий сир,авокадо', 'simple', 'own'),
      ('КАЛІФОРНІЯ З ВУГРЕМ', '/demo-suncity/kaliforniia-z-vuhrem.png', '220 г', 'Рис,норі, вугор, тобіка, огірок,авокадо', 'simple', 'own'),
      ('БІЛИЙ ДРАКОН', '/demo-suncity/bilyi-drakon.jpg', '220 г', 'Норі,рис,масляна,соус спайсі,сир Філадельфія,креветка тигрова,тобіка,огірок', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ КУНСЕЙ', '/demo-suncity/filadelfiia-kunsei.png', '260 г', 'Норі, рис Філадельфія, огірок, масляна', 'simple', 'own'),
      ('КАЛІФОРНІЯ КУНСЕЙ', '/demo-suncity/kaliforniia-kunsei.jpg', '220 г', 'Рис, норі, тобіко, масляна, огірок, авокадо, соус які', 'simple', 'own'),
      ('ФУТОМАКІ КУНСЕЙ', '/demo-suncity/futomaki-kunsei.jpg', '210 г', 'Норі,рис,Філадельфія,огірок,масляна,айсберг,соус чилі', 'simple', 'own'),
      ('КАЛІФОРНІЯ СМАЖЕНИЙ ЛОСОСЬ', '/demo-suncity/kaliforniia-smazhenyi-losos.jpg', '220 г', 'Норі, рис, філадельфія, авокадо, огірок, лосось смажений, тобіко', 'simple', 'own'),
      ('КАЛІФОРНІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', '/demo-suncity/kaliforniia-z-tyhrovoiu-krevetkoiu.jpg', '250 г', 'Норі, рис, філадельфія, огірок, авокадо, креветка варена, тобіко', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ ОМЛЕТ', '/demo-suncity/filadelfiia-omlet.jpg', '260 г', 'Норі, рис, омлет, філадельфія, лосось слабосолений', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ КЛАСІК', '/demo-suncity/filadelfiia-klasik.jpg', '260 г', 'Норі, рис, огірок, філадельфія, лосось свіжий', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ З ТУНЦЕМ', '/demo-suncity/filadelfiia-z-tuntsem.jpg', '260 г', 'Норі, рис, сир Філадельфія, огірок, тунець свіжий, унагі', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', '/demo-suncity/filadelfiia-z-tyhrovoiu-krevetkoiu.jpg', '260 г', 'Норі, рис, філадельфія, огірок, креветка', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ З ВУГРЕМ', '/demo-suncity/filadelfiia-z-vuhrem.jpg', '260 г', 'Норі, рис, огірок, Філадельфія, вугор, соус унагі, кунжут', 'simple', 'own'),
      ('ЧЕРВОНИЙ ДРАКОН', '/demo-suncity/chervonyi-drakon.jpg', '280 г', 'Норі, рис, сир Філадельфія, огірок, креветка, тобіко, лосось, соус солодкий чилі, кунжут', 'simple', 'own'),
      ('ЗОЛОТИЙ ДРАКОН', '/demo-suncity/zolotyi-drakon.jpg', '280 г', 'Норі, рис, сир Філадельфія, огірок, омлет, лосось, вугор, тобіко, соус унагі, кунжут', 'simple', 'own'),
      ('ЗЕЛЕНИЙ ДРАКОН', '/demo-suncity/zelenyi-drakon.jpg', '280 г', 'Норі, рис, сир Філадельфія, огірок, вугор, тобіко, авокадо, кунжут смажений, соус унагі', 'simple', 'own'),
      ('РОЛ ВЕСЕЛКА', '/demo-suncity/rol-veselka.jpg', '260 г', 'Норі, рис, сир Філадельфія, огірок, тобіко, лосось, вугор, тунець, креветка', 'simple', 'own'),
      ('СИР РОЯЛ DE LUX', '/demo-suncity/syr-roial-de-lux.jpg', '250 г', 'Рис, сир Філадельфія, сир Комо, сир Чеддер, соус унагі, сир Дор Блю', 'simple', 'own'),
      ('РОЛ ЧЕДДЕР', '/demo-suncity/rol-chedder.jpg', '240 г', 'Норі, рис, сир Філадельфія, сир Комо, сир Чеддер', 'simple', 'own'),
      ('РОЛ МАНГО', '/demo-suncity/rol-manho.jpg', '240 г', 'Норі, рис, сир Філадельфія, кунжут, манго, лосось обсмажений, солодкий чилі, соус Унагі', 'simple', 'own'),
      ('РОЛ КРЕВЕТКА ПАНКО', '/demo-suncity/rol-krevetka-panko.jpg', '250 г', 'Норі, рис, соус Які, креветка панко, огірок, сир Філадельфія, тобіко чорна', 'simple', 'own'),
      ('ФІЛАДЕЛЬФІЯ РОЯЛ DE LUX XXL', '/demo-suncity/filadelfiia-roial-de-lux-xxl.jpg', '290 г', 'Норі, рис, сир Філадельфія, огірок, лосось свіжий', 'simple', 'own'),
      ('РОЛ МАКІ З ОГІРКОМ', '/demo-suncity/rol-maki-z-ohirkom.jpg', '100 г', 'Норі, рис, огірок', 'simple', 'own'),
      ('РОЛ МАКІ З АВОКАДО', '/demo-suncity/rol-maki-z-avokado.jpg', '100 г', 'Норі, рис, авокадо', 'simple', 'own'),
      ('РОЛ МАКІ З ЛОСОСЕМ', '/demo-suncity/rol-maki-z-lososem.jpg', '110 г', 'Норі, рис, лосось', 'simple', 'own'),
      ('РОЛ МАКІ З ТУНЦЕМ', '/demo-suncity/rol-maki-z-tuntsem.jpg', '110 г', 'Норі, рис, тунець', 'simple', 'own'),
      ('РОЛ МАКІ З ВУГРЕМ', '/demo-suncity/rol-maki-z-vuhrem.jpg', '120 г', 'Норі, рис, вугор, соус Унагі, кунжут', 'simple', 'own'),
      ('РОЛ МАКІ ЗІ СМАЖЕНИМ ЛОСОСЕМ', '/demo-suncity/rol-maki-zi-smazhenym-lososem.jpg', '110 г', 'Норі, рис, лосось смажений', 'simple', 'own'),
      ('ФУТОМАКІ З ЛОСОСЕМ ТА МАНГО', '/demo-suncity/futomaki-z-lososem-ta-manho.jpg', '200 г', 'Норі, рис, сир Філадельфія, філе лосося , манго ,ікра тобіко, айсберг', 'simple', 'own'),
      ('ФУТОМАКІ З КОПЧЕНИМ ЛОСОСЕМ', '/demo-suncity/futomaki-z-kopchenym-lososem.jpg', '205 г', 'Норі, рис,сир Філадельфія, копчений лосось, огірок, айсберг, тобіко', 'simple', 'own'),
      ('ФУТОМАКІ З ТУНЦЕМ', '/demo-suncity/futomaki-z-tuntsem.jpg', '220 г', 'Норі, рис , сир Філадельфія, тунец , айсберг , ікра тобіко чорна , огірок , соус Унагі , кунжут', 'simple', 'own'),
      ('ФУТОМАКІ З КРАБ.ПАЛОЧКОЮ', '/demo-suncity/futomaki-z-krab-palochkoiu.jpg', '215 г', 'Норі, рис, сир Філадельфія, краб.палочка, огірок , ікра тобіко, айсберг, соус Які', 'simple', 'own'),
      ('ФУТОМАКІ З КРЕВЕТКОЮ', '/demo-suncity/futomaki-z-krevetkoiu.jpg', '220 г', 'Норі, рис, сир Філадельфія, креветка, пармезан, огірок, айсберг, ікра тобіка чорна, соус Чілі', 'simple', 'own'),
      ('ФУТОМАКІ З ВУГРЕМ', '/demo-suncity/futomaki-z-vuhrem.jpg', '220 г', 'Норі, рис, сир Філадельфія, вугор, огірок, ікра тобіко червона, айсберг, унагі, кунжут', 'simple', 'own'),
      ('ГУНКАН З КРЕВЕТКОЮ', '/demo-suncity/hunkan-z-krevetkoiu.jpg', '55 г', 'Норі, рис, креветка, соус Які', 'simple', 'own'),
      ('ГУНКАН З ЛОСОСЕМ', '/demo-suncity/hunkan-z-lososem.jpg', '55 г', 'Норі, рис, філе лосося, соус Які', 'simple', 'own'),
      ('ГУНКАН З ТУНЦЕМ', '/demo-suncity/hunkan-z-tuntsem.jpg', '55 г', 'Норі, рис, тунець', 'simple', 'own'),
      ('ГУНКАН З ЧУКОЮ', '/demo-suncity/hunkan-z-chukoiu.jpg', '60 г', 'Норі, рис, чука, соус горіховий, кунжут', 'simple', 'own'),
      ('ГУНКАН З ІКРОЮ', '/demo-suncity/hunkan-z-ikroiu.jpg', '40 г', 'Норі, рис, ікра тобіко', 'simple', 'own'),
      ('ГУНКАН З ВУГРЕМ', '/demo-suncity/hunkan-z-vuhrem.jpg', '40 г', 'Норі, рис, вугор, соус Унагі', 'simple', 'own'),
      ('ГУНКАН КУНСЕЙ', '/demo-suncity/hunkan-kunsei.jpg', '40 г', 'Норі, рис, масляна, соус Які', 'simple', 'own'),
      ('РОЛ З ЧУКОЮ І ЛОСОСЕМ', '/demo-suncity/rol-z-chukoiu-i-lososem.jpg', '250 г', 'Норі, рис, сир Філадельфія, огірок, філе лосося, чука, соус горіховий, кунжут', 'simple', 'own'),
      ('Ролл з чукою і креветкою', '/demo-suncity/roll-z-chukoiu-i-krevetkoiu.jpg', '250 г', 'Норі, Рис, Сир Філадельфія, Огірок,Креветка, Чука, Соус горіховий, Кунжут', 'simple', 'own'),
      ('Ролл з чукою і тунцем', '/demo-suncity/roll-z-chukoiu-i-tuntsem.jpg', '250 г', 'Норі, Рис,Сир Філадельфія, Огірок, Тунец, Чука, Соус горіховий, Кунжут', 'simple', 'own'),
      ('Ролл з чукою і вугрем', '/demo-suncity/roll-z-chukoiu-i-vuhrem.jpg', '250 г', 'Норі, Рис,Сир Філадельфія, Огірок, Вугор, Чука, Соус горіховий, Кунжут', 'simple', 'own'),
      ('Ролл з чукою і краб.палочкою', '/demo-suncity/roll-z-chukoiu-i-krab-palochkoiu.jpg', '250 г', 'Норі, Рис,Сир Філадельфія, Огірок, Крабова палочка, Чука, Соус горіховий, Кунжут', 'simple', 'own'),
      ('Філадельфія з копченим лососем', '/demo-suncity/filadelfiia-z-kopchenym-lososem.jpg', '260 г', 'Норі, рис , сир філадельфія, огірок , копчений лосось', 'simple', 'own'),
      ('Каліфорнія з копченим лососем', '/demo-suncity/kaliforniia-z-kopchenym-lososem.jpg', '230 г', 'Норі , рис , сир філадельфія, копчений лосось, авокадо, огірок, тобіко оранжева', 'simple', 'own'),
      ('Чеддер з лососем', '/demo-suncity/chedder-z-lososem.jpg', '260 г', 'Норі , рис , сир філадельфія, свіжий лосось, огірок, Чеддер , унагі', 'simple', 'own'),
      ('Чеддер з тунцем', '/demo-suncity/chedder-z-tuntsem.jpg', '260 г', 'Норі, рис , сир філадельфія, тунець , огірок , Чеддер , соус унагі', 'simple', 'own'),
      ('Чеддер з копченим лососем', '/demo-suncity/chedder-z-kopchenym-lososem.jpg', '260 г', 'Норі , рис , сир філадельфія, копчений лосось, огірок , Чеддер , соус унагі', 'simple', 'own'),
      ('Чеддер з вугрем', '/demo-suncity/chedder-z-vuhrem.jpg', '265 г', 'Норі , рис, сир філадельфія, вугор, огірок , Чеддер , соус унагі, кунжут', 'simple', 'own'),
      ('Чеддер Манго', '/demo-suncity/chedder-manho.jpg', '250 г', 'Норі , рис , сир філадельфія, манго , чеддер , соус унагі', 'simple', 'own'),
      ('Чеддер зі смаженим лососем', '/demo-suncity/chedder-zi-smazhenym-lososem.jpg', '260 г', 'Норі , рис, сир філадельфія, огірок , смажений лосось, чеддер, соус унагі', 'simple', 'own'),
      ('Чеддер з креветкою', '/demo-suncity/chedder-z-krevetkoiu.jpg', '260 г', 'Норі , рис , сир філадельфія, креветка , огірок , Чеддер , соус солодкий Чилі', 'simple', 'own'),
      ('Чеддер з крабовою палочкою', '/demo-suncity/chedder-z-krabovoiu-palochkoiu.jpg', '260 г', 'Норі, рис, сир філадельфія, крабова палочка , огірок , Чеддер, унагі', 'simple', 'own'),
      ('Чеддер зі смаженим тунцем', '/demo-suncity/chedder-zi-smazhenym-tuntsem.jpg', '260 г', 'Водорості норі, рис , сир філадельфія , огірок , смажений тунець , сир Чеддер , соус унагі', 'simple', 'own'),
      ('Каліфорнія зі смаженим тунцем', '/demo-suncity/kaliforniia-zi-smazhenym-tuntsem.jpg', '230 г', 'Водорості Норі, рис , сир філадельфія, смажений тунець, авокадо, огірок, кунжут.', 'simple', 'own'),
      ('Філадельфія зі смаженим тунцем', '/demo-suncity/filadelfiia-zi-smazhenym-tuntsem.jpg', '230 г', 'Водорості Норі, рис , сир філадельфія, смажений тунець, кунжут', 'simple', 'own'),
      ('Ролл з чукою і смаженим тунцем', '/demo-suncity/roll-z-chukoiu-i-smazhenym-tuntsem.jpg', '285 г', 'Водорості Норі, рис, сир філадельфія , огірок , крабова палочка, чука, соус горіховий, кунжут , смажений тунець', 'simple', 'own'),
      ('Футомакі зі смаженим тунцем', '/demo-suncity/futomaki-zi-smazhenym-tuntsem.jpg', '220 г', 'Водорості норі, рис, сир філадельфія, смажений тунець, огірок, ікра тобіко Червона, айсберг, соус унагі, кунжут', 'simple', 'own'),
      ('Футомакі зі смаженим лососем', '/demo-suncity/futomaki-zi-smazhenym-lososem.jpg', '220 г', 'Водорості Норі, рис, сир філадельфія, смажений лосось , огірок, ікра тобіко Червона, айсберг, соус унагі, кунжут', 'simple', 'own'),
      ('Філадельфія смажений лосось', '/demo-suncity/filadelfiia-smazhenyi-losos.jpg', '230 г', 'Водорості норі, рис , сир філадельфія, смажений лосось, кунжут', 'simple', 'own'),
      ('Дракон Каліграф', '/demo-suncity/drakon-kalihraf.jpg', '285 г', 'Водорості Норі, Рис, сир Філадельфія , огірок, Крабова паличка, тунець, ікра тобіко, соус унагі', 'simple', 'own'),
      ('Тигровий дракон', '/demo-suncity/tyhrovyi-drakon.jpg', '280 г', 'Водорості Норі, рис, Сир Філадельфія , огірок, вугор, ікра тобіко, креветка, соус чилі, кунжут', 'simple', 'own'),
      ('Нігірі лосось', '/demo-suncity/nihiri-losos.jpg', '50 г', 'Рис, водорості норі, філе лосося', 'simple', 'own'),
      ('Нігірі вугор', '/demo-suncity/nihiri-vuhor.jpg', '50 г', 'Рис, водорості норі, вугор', 'simple', 'own'),
      ('Нігірі креветка', '/demo-suncity/nihiri-krevetka.jpg', '40 г', 'Рис, Водорості норі, креветка.', 'simple', 'own'),
      ('Нігірі Тунець', '/demo-suncity/nihiri-tunets.png', '50 г', 'Рис, Водорості норі, тунець', 'simple', 'own'),
      ('Ролл від шефа', '/demo-suncity/roll-vid-shefa.jpg', '260 г', 'Водорості норі, рис, креветка, чеддер, сир філадельфія, огірок, соус унагі.', 'simple', 'own'),
      ('Ролл Аляска', '/demo-suncity/roll-aliaska.jpg', '260 г', 'Норі, рис, краб. палочка, креветка, авокадо, соус унагі, сир філадельфія, огірок', 'simple', 'own'),
      ('Кезюрі рол', '/demo-suncity/keziuri-rol.jpg', '260 г', 'Норі, рис, сир Філадельфія, огірок, лосось обсмажений, стружка тунця, кунжут.', 'simple', 'own'),
      ('Темпура з лососем', '/demo-suncity/tempura-z-lososem.jpg', '260 г', 'Норі, рис, сир філадельфія, огірок, філе лосося.', 'simple', 'own'),
      ('Темпура з вугрем', '/demo-suncity/tempura-z-vuhrem.jpg', '260 г', 'Норі, Рис, Сир філадельфія, огірок, вугор, кунжут, соус унагі, тобіка .', 'simple', 'own'),
      ('Темпура з креветкою', '/demo-suncity/tempura-z-krevetkoiu.jpg', '260 г', 'Норі, Рис, Сир філадельфія, огірок, креветка, соус чілі, тобіка.', 'simple', 'own'),
      ('Темпура с краб. палочкою', '/demo-suncity/tempura-s-krab-palochkoiu.jpg', '260 г', 'Норі, Рис, Сир філадельфія, огірок, краб. палочка, соус які, тобіка.', 'simple', 'own'),
      ('Темпура з тунцем', '/demo-suncity/tempura-z-tuntsem.jpg', '260 г', 'Норі, Сир Філадельфія, огірок, Тунець, соус унагі, тобіка .', 'simple', 'own'),
      ('Рол Дог', '/demo-suncity/rol-doh.jpg', '260 г', 'Норі, Сир філадельфія, рис, кунжут, соус кимчи, креветка, філе лосося, соус унагі.', 'simple', 'own'),
      ('Удон смажений лосось 420г', '/demo-suncity/udon-smazhenyi-losos-420h.jpg', '420 г', 'Локшина, філе лосося, огірок, болгарський перець, кунжут. Смачна та ароматна локшина з лососем', 'simple', 'own'),
      ('Удон смажений тунець 420г', '/demo-suncity/udon-smazhenyi-tunets-420h.jpg', '420 г', 'Локшина, тунець, огірок, болгарський, кунжут. Смачна та ситна локшина з тунцем', 'simple', 'own'),
      ('Удон з креветкою 400г', '/demo-suncity/udon-z-krevetkoiu-400h.jpg', '400 г', 'Локшина, креветка, огірок, болгарський перець, кунжут, соус чілі. Смачна та ароматна локшина з креветкою', 'simple', 'own'),
      ('Веган Удон 460г', '/demo-suncity/vehan-udon-460h.jpg', '460 г', 'Локшина, огірок, болгарський перець, кунжут, горіховий соус. Локшина йде без мяса', 'simple', 'own'),
      ('Удон з мідією 430г', '/demo-suncity/udon-z-midiieiu-430h.jpg', '430 г', 'Локшина, мідії, огірок, болгарський перець, кунжут. Смачна локшина з мідіями', 'simple', 'own'),
      ('Удон Морський коктейль 430г', '/demo-suncity/udon-morskyi-kokteil-430h.jpg', '430 г', 'Локшина, кальмар, восьминіг, креветка, мідії , огірок, болгарський перець, кунжут.', 'simple', 'own'),
      ('Удон восьминіжка 430г', '/demo-suncity/udon-vosmynizhka-430h.jpg', '430 г', 'Локшина, восьминіг, огірок, болгарський перець, кунжут.', 'simple', 'own'),
      ('Сан Сет 1150г', '/demo-suncity/san-set-1150h.jpg', '1150 г', 'Золотий Дракон Каліфорнія з креветкою Філадельфія з тунцем Чеддер Макі з авокадо', 'simple', 'own'),
      ('Каліфорнія сет 690г', '/demo-suncity/kaliforniia-set-690h.jpg', '690 г', 'Каліфорнія лосось Каліфорнія смажений тунець Каліфорнія з креветкою', 'simple', 'own'),
      ('Лосось сет 890 г', '/demo-suncity/losos-set-890-h.jpg', '890 г', 'Рол Манго Філадельфія класік Філадельфія омлет макі з лососем', 'simple', 'own'),
      ('Сет Філадельфія XXL 1320 г', '/demo-suncity/set-filadelfiia-xxl-1320-h.jpg', '1320 г', 'Чеддер Зелений дракон Філадельфія з тунцем Веселка Манго', 'simple', 'own'),
      ('Тріо сет 680 г', '/demo-suncity/trio-set-680-h.jpg', '680 г', 'Рол сир роял DE LUX Рол креветка панко Каліфорнія смажений лосось', 'simple', 'own'),
      ('Сет Преміум 1660г', '/demo-suncity/set-premium-1660h.jpg', '1660 г', 'Золотий дракон Червоний дракон Каліфорнія креветка Філадельфія вугор рол Веселка Макі з огірком Сир роял DE LUX', 'simple', 'own'),
      ('Дракон СЕТ 830г', '/demo-suncity/drakon-set-830h.jpg', '830 г', 'Червоний дракон Золотий дракон Зелений дракон', 'simple', 'own'),
      ('Сет Сирний 1040г', '/demo-suncity/set-syrnyi-1040h.jpg', '1040 г', 'Чеддер з крабовою палочкою Чеддер з лососем Чеддер з креветкою Чеддер з тунцем', 'simple', 'own'),
      ('Сет Філадельфія MAXI', '/demo-suncity/set-filadelfiia-maxi.jpg', '1300 г', 'Філадельфія з креветкою Філадельфія з тунцем Філадельфія з лососем Філадельфія з копченим лососем Філадельфія з вугрем', 'simple', 'own'),
      ('Сет Хіяши 760г', '/demo-suncity/set-khiiashy-760h.jpg', '760 г', 'Рол з чукою і лососем Рол з чукою і креветкою Рол з чукою і тунцем', 'simple', 'own'),
      ('Сет Драконів MAX', '/demo-suncity/set-drakoniv-max.jpg', '1440 г', 'Золотий дракон Червоний Дракон Зелений дракон Дракон каліграф Тигровий Дракон', 'simple', 'own'),
      ('Бургер з запеченим філе', '/demo-suncity/burher-z-zapechenym-file.jpg', NULL, 'Булка кругла з кунжутом , запечене філе, огірок солений, кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з запеченим філе та сиром', '/demo-suncity/burher-z-zapechenym-file-ta-syrom.jpg', NULL, 'Булка кругла з кунжутом , запечене філе, огірок солений, сир тостовий , кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з запеченим філе та подвійним сиром', '/demo-suncity/burher-z-zapechenym-file-ta-podviinym-syrom.jpg', NULL, 'Булка кругла з кунжутом , запечене філе, огірок солений, сир тостовий(2 шт) , кетчуп, майонез.', 'simple', 'own'),
      ('Шаурма', '/demo-suncity/shaurma.jpg', NULL, 'Лаваш, філе куряче запечене, капуста , морква по-корейськи, огірок солений, майонез, гірчиця, соус сацебелі, соус часниковий. Смачна та ситна', 'simple', 'own'),
      ('Шаурма з сиром', '/demo-suncity/shaurma-z-syrom.jpg', NULL, 'Лаваш, філе куряче запечене, капуста , морква по-корейськи, огірок солений,сир тостовий 2 шт, майонез, гірчиця, соус сацебелі, соус часниковий. Смачна та сита', 'simple', 'own'),
      ('Креветка Панко 10 шт', '/demo-suncity/krevetka-panko-10-sht.jpg', '660 г', 'Креветка 10шт', 'simple', 'own'),
      ('Хот дог в лаваші з 2 сосисками', '/demo-suncity/khot-doh-v-lavashi-z-2-sosyskamy.jpg', NULL, 'Лаваш, сосиска 2 шт, капуста , морква по-корейськи, огірок солений, майонез, гірчиця, кетчуп. Смачний та ситий', 'simple', 'own'),
      ('Хот дог французький', '/demo-suncity/khot-doh-frantsuzkyi.jpg', NULL, 'Булка для французького ского хот- дога біла, ковбаска Братвурська, кетчуп, майонез, гірчиця. Смачний та ситий', 'simple', 'own'),
      ('Хот дог американский', '/demo-suncity/khot-doh-amerykanskyi.jpg', NULL, 'Булка для хот дога з розрізом, сосиска, капуста, морква по-корейськи, кетчуп, майонез, гірчиця. Смачний та ситий', 'simple', 'own'),
      ('Бургер з курячою котлетою', '/demo-suncity/burher-z-kuriachoiu-kotletoiu.jpg', NULL, 'Булка кругла з кунжутом, котлета куряча , огірок солений, кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з курячою котлетою та сиром', '/demo-suncity/burher-z-kuriachoiu-kotletoiu-ta-syrom.jpg', NULL, 'Булка кругла з кунжутом , котлета куряча , огірок солений, сир тостовий , кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з курячою котлетою та подвійним сиром', '/demo-suncity/burher-z-kuriachoiu-kotletoiu-ta-podviinym-syrom.jpg', NULL, 'Булка кругла з кунжутом , котлета куряча , огірок солений, сир тостовий(2 шт) , кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з яловичою котлетою', '/demo-suncity/burher-z-ialovychoiu-kotletoiu.jpg', NULL, 'Булка кругла з кунжутом, котлета яловича , огірок солений, кетчуп, майонез.', 'simple', 'own'),
      ('Бургер Sun City з яловичою котлетою', '/demo-suncity/burher-sun-city-z-ialovychoiu-kotletoiu.jpg', NULL, 'Булка кругла з кунжутом, реліш, котлета яловича, листя салату, помідор, сир тостовий, цибуля маринована, майонез кетчуп.', 'simple', 'own'),
      ('Бургер Sun City з курячою котлетою', '/demo-suncity/burher-sun-city-z-kuriachoiu-kotletoiu.jpg', NULL, 'Булка кругла з кунжутом, реліш, котлета куряча , листя салату, помідор, сир тостовий, цибуля маринована, майонез кетчуп.', 'simple', 'own'),
      ('Бургер з яловичою котлетою та сиром', '/demo-suncity/burher-z-ialovychoiu-kotletoiu-ta-syrom.jpg', NULL, 'Булка кругла з кунжутом, котлета яловича ,сир тостовий, огірок солений, кетчуп, майонез.', 'simple', 'own'),
      ('Бургер з яловичою котлетою та подвійним сиром', '/demo-suncity/burher-z-ialovychoiu-kotletoiu-ta-podviinym-syrom.jpg', NULL, 'Булка кругла з кунжутом, котлета яловича ,сир тостовий(2 шт) , огірок солений, кетчуп, майонез.', 'simple', 'own'),
      ('Суши бургер з лососем 330г', '/demo-suncity/sushy-burher-z-lososem-330h.jpg', '330 г', 'Рис, сир Філадельфія, огірок,айсберг, філе лосося, сир чеддер, соус які, соус унагі, кунжут.', 'simple', 'own'),
      ('Суши бургер з креветкою 330г', '/demo-suncity/sushy-burher-z-krevetkoiu-330h.jpg', '330 г', 'Філадельфія, огірок, айсберг, креветка, сир чеддер, спайсі, соус унагі, кунжут.', 'simple', 'own'),
      ('Black суші бургер', '/demo-suncity/black-sushi-burher.jpg', '330 г', 'Смачний та ситий суші бургер', 'simple', 'own'),
      ('Преміум ROYAL сет від шефа 3000г', '/demo-suncity/premium-royal-set-vid-shefa-3000h.jpg', '3000 г', 'Роли 8 шт Нігірі 12 шт Гункани 6 шт Святкове упакування Подарунок від шефа', 'simple', 'own'),
      ('Темпура XXL сет 1300г', '/demo-suncity/tempura-xxl-set-1300h.jpg', '1300 г', 'Темпура з лососем Темпура з вугрем Темпура з креветкою Темпура з краб.паличкою Темпура з тунцем', 'simple', 'own'),
      ('Тріо темпура сет 780г', '/demo-suncity/trio-tempura-set-780h.jpg', '780 г', 'Темпура з тунцем Темпура з лососем Темпура з креветкою', 'simple', 'own'),
      ('Міх сет 990 г', '/demo-suncity/mikh-set-990-h.jpg', '990 г', 'Кезюрі Футомакі смажений лосось Ролл з чукою і тунцем Чеддер з вугрем', 'simple', 'own'),
      ('Класичний сет 1035г', '/demo-suncity/klasychnyi-set-1035h.jpg', '1035 г', 'Філадельфія класік Каліфорнія з копченим лососем Ролл від шефа Дракон Каліграф', 'simple', 'own'),
      ('Гурман сет 875 г', '/demo-suncity/hurman-set-875-h.jpg', '980 г', 'Ролл веган Чеддер з креветкою Гункан з ікрою 2 шт Золотий дракон Нігірі лосось 2 шт Нігірі креветка 2 шт', 'simple', 'own'),
      ('Дабл суші сет 510г', '/demo-suncity/dabl-sushi-set-510h.jpg', '510 г', 'Нігірі креветка 2 шт Нігірі лосось 2 шт Нігірі вугор 2 шт Гункан з чукою 2 шт Гункан з тунцем 2 шт', 'simple', 'own'),
      ('Фаворит сет 800 г', '/demo-suncity/favoryt-set-800-h.jpg', '800 г', 'Ролл Аляска Тигровий дракон Філадельфія з вугрем', 'simple', 'own'),
      ('Креветка 4х сет 880 г', '/demo-suncity/krevetka-4kh-set-880-h.jpg', '880 г', 'Чеддер з креветкою Філадельфія з креветкою Ролл з чукою і креветкою Гункан з креветкою 2 шт', 'simple', 'own'),
      ('Лосось 4х сет 845г', '/demo-suncity/losos-4kh-set-845h.jpg', '880 г', 'Чеддер з лососем Ролл з чукою і смаженим лососем Каліфорнія лосось Гункан з лососем 2 шт', 'simple', 'own'),
      ('Вугор 4х сет 875 г', '/demo-suncity/vuhor-4kh-set-875-h.jpg', '875 г', 'Чеддер з вугрем Філадельфія з вугрем Ролл з чукою і вугрем Нігірі вугор 2 шт', 'simple', 'own'),
      ('Тунец 4х сет 875 г', '/demo-suncity/tunets-4kh-set-875-h.jpg', '875 г', 'Каліфорнія смажений тунець Ролл з чукою і смаженим тунцем Чеддер з тунцем Нігірі тунець 2 шт', 'simple', 'own'),
      ('Люкс сет 2425 г', '/demo-suncity/liuks-set-2425-h.jpg', '2425 г', 'Золотий дракон Філадельфія класік Філадельфія вугор Філадельфія креветка Тигровий дракон Червоний дракон Дракон Каліграф Філадельфія з копченим лососем Філадельфі з тунцем', 'simple', 'own'),
      ('Курка', '/demo-suncity/kurka.jpg', NULL, 'Свіжа, запашна та з золотою шкоринкою', 'simple', 'own'),
      ('Крило', '/demo-suncity/krylo.jpg', NULL, 'Свіжі та запашні крильця з золотистою шкоринкою', 'simple', 'own'),
      ('Бедро', '/demo-suncity/bedro.jpg', NULL, 'Свіже, запашне та з хрусткою шкоринкою', 'simple', 'own'),
      ('Нагетси', '/demo-suncity/nahetsy.jpg', NULL, NULL, 'simple', 'own'),
      ('Картопля Фрі', '/demo-suncity/kartoplia-fri.jpg', NULL, 'Картопля Фрі. Смачна та хрустка', 'simple', 'own'),
      ('Картопля по-селянськи', '/demo-suncity/kartoplia-po-seliansky.jpg', NULL, 'Картопля по-селянськи. Смачна та хрустка', 'simple', 'own'),
      ('Double Meet', '/demo-suncity/double-meet.jpg', NULL, '50% Папероні 50% Fire', 'simple', 'own'),
      ('Double Fish', '/demo-suncity/double-fish.jpg', NULL, '50% Філадельфія 50% Маринара', 'simple', 'own'),
      ('4 сира', '/demo-suncity/4-syra.jpg', NULL, 'Сир ДорБлю Сир Моцарела Сир Пармезан Сир Чеддер Вершковий соус', 'simple', 'own'),
      ('Веган', '/demo-suncity/vehan.jpg', NULL, 'Гриби Болгарський перець Помідор Ананас Кукурудза Моцарела Маслини Томатний соус', 'simple', 'own'),
      ('Пепероні', '/demo-suncity/peperoni.jpg', NULL, 'Сир Чеддер Пепероні Помідор Сир Моцарела Томатний Соус', 'simple', 'own'),
      ('Філадельфія', '/demo-suncity/filadelfiia.jpg', NULL, 'Філе лосося Помідор Сир Чеддер Лимон Оливки Соус вершковий', 'simple', 'own'),
      ('Маринара', '/demo-suncity/marynara.jpg', NULL, 'Морський коктейль Цибуля Помідор Сир Моцарела Маслини Вершковий соус', 'simple', 'own'),
      ('Дитяча', '/demo-suncity/dytiacha.jpg', NULL, 'Філе куряче Кукурудза Сир Чеддер Соус Вершковий', 'simple', 'own'),
      ('Fire', '/demo-suncity/fire.jpg', NULL, 'Балик Мисливські ковбаски Кукурудза Помідор Сир Моцарела Перець Чілі Томатний соус', 'simple', 'own'),
      ('Double Chicken', '/demo-suncity/double-chicken.jpg', NULL, '50% Жульєн 50% Дитяча', 'simple', 'own'),
      ('Жульєн', '/demo-suncity/zhulien.jpg', NULL, 'Гриби Сир Чеддер Цибуля Сир Моцарела Філе куряче Помідор Вершковий соус', 'simple', 'own'),
      ('Double Cheese', '/demo-suncity/double-cheese.jpg', NULL, 'Сир Чеддер Бекон Філе куряче Помідор Сир Моцарела Вершковий соус', 'simple', 'own'),
      ('М''ясна', '/demo-suncity/miasna.jpg', NULL, 'Салямі Бекон Мисливські ковбаски Філе куряче Сир Моцарела Помідор Томатний Соус', 'simple', 'own'),
      ('Дольче', '/demo-suncity/dolche.jpg', NULL, 'Гриби Болгарський перець Філе куряче Кукурудза Сир Моцарела Вершковий соус', 'simple', 'own'),
      ('Чотири сезона', '/demo-suncity/chotyry-sezona.jpg', NULL, 'Сир Моцарела гриби філе куряче болгарський перець кукурудза балик маслини сир Чеддер томатний соус', 'simple', 'own'),
      ('Алегрі', '/demo-suncity/alehri.jpg', NULL, 'Сир Моцарела цибуля мисливські ковбаски огірок солений сир Чеддер томатний соус', 'simple', 'own'),
      ('Гавайська', '/demo-suncity/havaiska.jpg', NULL, 'Моцарела філе куряче ананас помідор сир Чеддер томатний соус', 'simple', 'own'),
      ('Шаурма по-домашньому з ковбаскою', '/demo-suncity/shaurma-po-domashnomu-z-kovbaskoiu.jpg', NULL, 'Смашна та соковита шаурма Лаваш, капуста, морква ,кукурудза, ковбаска, майонез, кетчуп', 'simple', 'own'),
      ('Деруни', '/demo-suncity/deruny.jpg', NULL, 'Смачні деруни зі сметаною', 'simple', 'own'),
      ('Картопляні кульки', '/demo-suncity/kartopliani-kulky.jpg', NULL, 'Картопляні кульки + соус', 'simple', 'own'),
      ('Цибулеві кільця', '/demo-suncity/tsybulevi-kiltsia.jpg', NULL, 'Цибулеві кільця 13 шт + соус', 'simple', 'own'),
      ('Крильця Sun City', '/demo-suncity/kryltsia-sun-city.jpg', NULL, 'Крильця 7 шт + соус', 'simple', 'own'),
      ('Стейк меню', '/demo-suncity/steik-meniu.jpg', NULL, 'Ідеально підійде на обід Стейк, картопля та салат з капусти', 'simple', 'own'),
      ('Міні ланч бокс', '/demo-suncity/mini-lanch-boks.jpg', NULL, 'Бургер з курячою котлетою + сир - 1 шт. Картопля по-селянські - 1 порція Нагетси - 1 порція Ідеальний вибір для перекусу на роботі', 'simple', 'own'),
      ('Маргарита', '/demo-suncity/marharyta.jpg', NULL, 'Соус томатний Моцарелла Томати Базилік', 'simple', 'own'),
      ('Капрічоза', '/demo-suncity/kaprichoza.jpg', NULL, 'Соус томатний Гриби Чеддер Балик Часникова олія Моцарелла Болгарський перець', 'simple', 'own'),
      ('Прошутто', '/demo-suncity/proshutto.jpg', NULL, 'Соус томатний Прошутто Томати Сулугуні Пармезан Чеддер Салат', 'simple', 'own'),
      ('Прошутто крудо', '/demo-suncity/proshutto-krudo.jpg', NULL, 'Вершковий соус Томати Айсберг Філе куряче (Мариноване) Прошутто крудо Сулугуні', 'simple', 'own'),
      ('Креветка Дор-Блю', '/demo-suncity/krevetka-dor-bliu.jpg', NULL, 'Соус шпинатний Моцарелла Оливки Креветка тигрова ДорБлю Маслини', 'simple', 'own'),
      ('Sun City', '/demo-suncity/sun-city.jpg', NULL, 'Вершковий соус Прошутто-крудо Філе куряче(мариноване) Айсберг Цибуля Моцарела', 'simple', 'own'),
      ('Салямі', '/demo-suncity/saliami.jpg', NULL, 'Соус томатний Салямі Чедер Томати Моцарелла', 'simple', 'own'),
      ('Тунець', '/demo-suncity/tunets.jpg', NULL, 'Вершковий соус Тунець Томати Оливки Чеддер', 'simple', 'own'),
      ('Вулкан', '/demo-suncity/vulkan.jpg', NULL, 'Мисливські ковбаски Чедер Моцарелла Шпинатний соус Томати', 'simple', 'own'),
      ('Чіназес', '/demo-suncity/chinazes.jpg', NULL, 'Копчене філе Бекон Моцарела Мікс салату(можлива заміна на айсберг) Вершковий соус', 'simple', 'own'),
      ('Палермо', '/demo-suncity/palermo.jpg', NULL, 'Прошутто ДорБлю Маслини Томати Авокадо Сир Моцарела Вершковий соус', 'simple', 'own'),
      ('Рол Укроп з комо', '/demo-suncity/rol-ukrop-z-komo.jpg', NULL, 'Сало Рис Сир комо Огірок маринований Хрін', 'simple', 'own'),
      ('Рол Укроп з філадельфією', '/demo-suncity/rol-ukrop-z-filadelfiieiu.jpg', NULL, 'Рис Сало Огірок маринований Філадельфія Хрін Цибуля', 'simple', 'own'),
      ('Рол Мехіко', '/demo-suncity/rol-mekhiko.jpg', '310 г', '-Норі -Рис -Філадельфія -Болгарський перець -Лосось обсмажений -Соус спайсі -Соус ШріРача', 'simple', 'own'),
      ('Рол grill cheese з лососем', '/demo-suncity/rol-grill-cheese-z-lososem.jpg', '300 г', '-Норі -Рис -Філадельфія -Авокадо -Лосось обсмажений -Соус унагі -Соус спайсі', 'simple', 'own'),
      ('Рол Тоторі', '/demo-suncity/rol-totori.jpg', '310 г', '-Норі -Рис -Філадельфія -Огірок -Авокадо -Копчена курка -Соус які -Соус шрі – рачі -Кунжут -Унагі', 'simple', 'own'),
      ('Рол чеддер з копченою куркою', '/demo-suncity/rol-chedder-z-kopchenoiu-kurkoiu.jpg', '280 г', '-Рис -Норі -Огірок -Копчена курка -Чеддер -Унагі -Філадельфія', 'simple', 'own'),
      ('Рол лосось Махі', '/demo-suncity/rol-losos-makhi.jpg', '270 г', '-Норі -Рис -Філадельфія -Лосось свіжий', 'simple', 'own'),
      ('Рол Тунець Махі 260г', '/demo-suncity/rol-tunets-makhi-260h.jpg', NULL, '-Норі -Рис -Філадельфія -Тунець Унагі', 'simple', 'own'),
      ('Рол Вугор Махі 280г', '/demo-suncity/rol-vuhor-makhi-280h.jpg', NULL, '-Норі -Рис -Філадельфія -Вугор -Унагі -Кунжут', 'simple', 'own'),
      ('Рол Креветка Махі 280г', '/demo-suncity/rol-krevetka-makhi-280h.jpg', NULL, '-Норі -Рис -Філадельфія -Креветка -Сол.чилі', 'simple', 'own'),
      ('Рол Копчений лосось Махі 260г', '/demo-suncity/rol-kopchenyi-losos-makhi-260h.jpg', NULL, '-Норі -Рис -Філадельфія -Копчений лосось', 'simple', 'own'),
      ('Рол філадельфія Cheese', '/demo-suncity/rol-filadelfiia-cheese.jpg', '320 г', '-Рис -Норі -Філадельфія -Авокадо -Лосось -Чеддер -Пармезан', 'simple', 'own'),
      ('Футомак з коп. куркою та болг.перцем 260г', '/demo-suncity/futomak-z-kop-kurkoiu-ta-bolh-pertsem-260h.jpg', NULL, '-Норі -Рис -Філадельфія -Копчена курка -Болг.перець -Салат -Унагі -Кунжут', 'simple', 'own'),
      ('Рол каліфорнія Chicken 210г', '/demo-suncity/rol-kaliforniia-chicken-210h.jpg', NULL, '-Норі -Рис -Філадельфія -Копчена курка -Авокадо -Огірок -Кунжут', 'simple', 'own'),
      ('Рол Тропік', '/demo-suncity/rol-tropik.jpg', '280 г', 'норі,рис,філадельфія,апельсин,лосось свіжий', 'simple', 'own'),
      ('Рол Фрутіс', '/demo-suncity/rol-frutis.jpg', '290 г', 'Норі,рис,філадельфія,ківі,лосось копчений', 'simple', 'own'),
      ('Рол Спайсі Блек', '/demo-suncity/rol-spaisi-blek.jpg', '200 г', 'Норі,рис,Чеддер,лосось,соус спайсі, сир Філадельфія', 'simple', 'own'),
      ('Кето Рол', '/demo-suncity/keto-rol.jpg', '300 г', 'норі,лосось,тунець,вугор,креветка,філадельфія,унагі', 'simple', 'own'),
      ('Салат з чукою лососем та авокадо', '/demo-suncity/salat-z-chukoiu-lososem-ta-avokado.jpg', NULL, 'Чука,кунжут,лосось,авокадо,соус горіховий', 'simple', 'own'),
      ('Салат з чукою лососем і манго', '/demo-suncity/salat-z-chukoiu-lososem-i-manho.jpg', NULL, 'Чука,манго,лосось,кунжут,соус горіховий', 'simple', 'own'),
      ('Салат з чукою і тунцем', '/demo-suncity/salat-z-chukoiu-i-tuntsem.jpg', NULL, 'Чука,тунець,кунжут,горіховий соус, крабова паличка', 'simple', 'own'),
      ('Салат з чукою і креветкою', '/demo-suncity/salat-z-chukoiu-i-krevetkoiu.jpg', NULL, 'Чука,креветка,кунжут,соус чилі', 'simple', 'own'),
      ('Салат з чукою і копченим лососем', '/demo-suncity/salat-z-chukoiu-i-kopchenym-lososem.jpg', NULL, 'Чука,копчений лосось,кунжут,соус чилі', 'simple', 'own'),
      ('Салат з чукою і смаженим лососем', '/demo-suncity/salat-z-chukoiu-i-smazhenym-lososem.jpg', NULL, 'Чука,смажений лосось,кунжут,соус чилі', 'simple', 'own'),
      ('Темпура кунсей', '/demo-suncity/tempura-kunsei.jpg', NULL, 'норі,рис,філадельфія,огірок,масляна', 'simple', 'own'),
      ('Сет філадельфія класік', '/demo-suncity/set-filadelfiia-klasik.jpg', NULL, 'Філадельфія класік Філадельфія з вугрем Філадельфія з омлетом', 'simple', 'own'),
      ('Рол чікен філадельфія', '/demo-suncity/rol-chiken-filadelfiia.jpg', NULL, '- Норі - Рис - Сир філа - Курка - Огірок - Унагі - Кунжут', 'simple', 'own'),
      ('Суші пончик з креветкою', '/demo-suncity/sushi-ponchyk-z-krevetkoiu.jpg', '160 г', 'Рис Сир Філадельфія Креветка Соус Чилі Кунжут', 'simple', 'own'),
      ('Суші пончик з лососем', '/demo-suncity/sushi-ponchyk-z-lososem.jpg', '160 г', 'Рис Сир Філадельфія Лосось Кунжут', 'simple', 'own'),
      ('Суші пончик Чеддер', '/demo-suncity/sushi-ponchyk-chedder.jpg', '160 г', 'Рис Сир Філадельфія Сир Чедер Соус Унагі Кунжут', 'simple', 'own'),
      ('Суші пончик з вугрем', '/demo-suncity/sushi-ponchyk-z-vuhrem.jpg', '160 г', 'Рис Сир Філадельфія Вугор Соус Унагі Кунжут', 'simple', 'own'),
      ('Суши пончик з тунцем', '/demo-suncity/sushy-ponchyk-z-tuntsem.jpg', '160 г', 'Рис Сир Філадельфія Тунець Соус Унагі Кунжут', 'simple', 'own'),
      ('Кальмар', '/demo-suncity/kalmar.jpg', NULL, NULL, 'simple', 'own'),
      ('Паляниця', '/demo-suncity/palianytsia.jpg', NULL, 'Вершковий соус Моцарела ДорБлю Чедер Пармезан Часникова олія Філе мариноване', 'simple', 'own'),
      ('Хот дог в лаваші з 3 сосисками', '/demo-suncity/khot-doh-v-lavashi-z-3-sosyskamy.jpg', NULL, 'Лаваш, сосиска 3 шт, капуста , морква по-корейськи, огірок солений, майонез, гірчиця, кетчуп. Смачний та ситий', 'simple', 'own'),
      ('Карбонара', '/demo-suncity/karbonara.jpg', NULL, 'Вершковий соус, моцарелла, бекон, балик, жовток сирий', 'simple', 'own'),
      ('Стейк лосось меню', '/demo-suncity/steik-losos-meniu.jpg', NULL, 'Лосось,спаржева квасоля,шматочки лосося,соус унагі', 'simple', 'own'),
      ('Фрі бокс', '/demo-suncity/fri-boks.jpg', NULL, 'картопля фрі сирні палички нагетси', 'simple', 'own'),
      ('Фрі бокс XXL', '/demo-suncity/fri-boks-xxl.jpg', NULL, 'картопля фрі 2 порції сирні палички 2 порції нагетси 2 порції цибулеві кільця 2 порції крильця Sun City 1 порції', 'simple', 'own'),
      ('Сет Макі', '/demo-suncity/set-maki.jpg', NULL, 'Рол макі огірок Авокадо Лосось свіжий Лосось смажений Вугор Тунець', 'simple', 'own'),
      ('Сет Драконів Махі ХХЛ', '/demo-suncity/set-drakoniv-makhi-khkhl.jpg', NULL, 'Золотий дракон Червоний Дракон Зелений дракон Дракон каліграф Тигровий дракон Білий дракон', 'simple', 'own'),
      ('Філадельфія кунсей сет', '/demo-suncity/filadelfiia-kunsei-set.jpg', NULL, 'Філадельфія вугор Філадельфія класік Філадельфія кунсей', 'simple', 'own'),
      ('Прошуто Ананас', '/demo-suncity/proshuto-ananas.jpg', NULL, 'Ананас Соус вершковий Прошутто Бекон Чедер Моцарелла', 'simple', 'own'),
      ('Чізбургер', '/demo-suncity/chizburher.jpg', NULL, 'Бекон Балик Томати Огірок солений Цибуля Моцарелла Сир тостовий', 'simple', 'own'),
      ('Піца з лисичками', '/demo-suncity/pitsa-z-lysychkamy.jpg', NULL, 'Вершковий соус Моцарела Шампіньйони Пармезан Лисичкі Вершки', 'simple', 'own'),
      ('Діпи картопляні', '/demo-suncity/dipy-kartopliani.jpg', NULL, NULL, 'simple', 'own'),
      ('Сирні палички', '/demo-suncity/syrni-palychky.jpg', NULL, 'Сирні палички 5 шт', 'simple', 'own'),
      ('Фрі меню', '/demo-suncity/fri-meniu.jpg', NULL, 'картопля фрі,салямі', 'simple', 'own'),
      ('Меню по-селянські', '/demo-suncity/meniu-po-selianski.jpg', NULL, 'Картопля по селянські, салямі,огірок солений', 'simple', 'own'),
      ('Double бургер', '/demo-suncity/double-burher.jpg', NULL, 'Котлета на вибір 2 шт(яловича або куряча), сир 2шт, соус бургер, огірок солений', 'simple', 'own'),
      ('Сет Футомакі', '/demo-suncity/set-futomaki.jpg', NULL, 'Футомакі з лососем та манго Футомакі з копченим лососем Футомакі з креветкою Футомакі з крабовою паличкою', 'simple', 'own'),
      ('Темпура фірмова', '/demo-suncity/tempura-firmova.jpg', NULL, 'Норі, рис, сир Філадельфія, огірок, філе лосося, креветка, сир чеддер, тобіка, омлет, Чилі, кунжут', 'simple', 'own'),
      ('Суші бургер Кунсей', '/demo-suncity/sushi-burher-kunsei.jpg', NULL, 'Філадельфія, рис, огірок, айсберг, чеддер, соус які, масляна, соус унагі, кунжут', 'simple', 'own'),
      ('Sun Fri', '/demo-suncity/sun-fri.jpg', NULL, 'Салямі Бекон Мисливські ковбаски Філе куряче Сир Моцарела Помідор Томатний Соус Картопля фрі', 'simple', 'own'),
      ('Шаурма по Царськи', '/demo-suncity/shaurma-po-tsarsky.jpg', NULL, 'Лаваш, філе куряче запечене, кукурудза, помідор, сир, наші фірмові авторські соуси', 'simple', 'own'),
      ('Шаурма Фрі', '/demo-suncity/shaurma-fri.jpg', NULL, 'Лаваш, філе куряче, фрі, сир, помідр, соус', 'simple', 'own'),
      ('Піца Ягідна', '/demo-suncity/pitsa-iahidna.jpg', NULL, 'Паста Raffaello, лохина, полуниця, ожина, шоколад', 'simple', 'own'),
      ('Піца Фісташкова', '/demo-suncity/pitsa-fistashkova.jpg', NULL, 'Паста фісташкова, ананас , виноград, лохина, шоколад', 'simple', 'own'),
      ('Піца Фруктова', '/demo-suncity/pitsa-fruktova.jpg', NULL, 'Горіхова паста, ківі, ананас, манго, кокосова стружка', 'simple', 'own'),
      ('Бос BBQ', '/demo-suncity/bos-bbq.jpg', NULL, 'Соус Барбекю Балик Гриби Цибля Помідор Сир Чедер', 'simple', 'own'),
      ('BBQ Gold', '/demo-suncity/bbq-gold.jpg', NULL, 'Соус Барбекю, куряче філе, болгарський перець, кукурудза, помідор, сир Моцарела, сир Чедер, ковбасний борт', 'simple', 'own'),
      ('Бургер гриль', '/demo-suncity/burher-hryl.jpg', NULL, 'Булка з кунжутом, бекон, подвійний сир, листя салату, помідор, фірмовий соус', 'simple', 'own'),
      ('Квадро 4 сира', '/demo-suncity/kvadro-4-syra.jpg', NULL, 'Сир ДорБлю Сир Моцарела Сир Пармезан Сир Чеддер Вершковий соус', 'simple', 'own'),
      ('Квадро Веган', '/demo-suncity/kvadro-vehan.jpg', NULL, 'Гриби Болгарський перець Помідор Ананас Кукурудза Моцарела Маслини Томатний соус', 'simple', 'own'),
      ('Квадро Пепероні', '/demo-suncity/kvadro-peperoni.jpg', NULL, 'Сир Чеддер Пепероні Помідор Сир Моцарела Томатний Соус', 'simple', 'own'),
      ('Квадро Філадельфія', '/demo-suncity/kvadro-filadelfiia.jpg', NULL, 'Філе лосося Помідор Сир Чеддер Лимон Оливки Соус вершковий', 'simple', 'own'),
      ('Квадро Маринара', '/demo-suncity/kvadro-marynara.jpg', NULL, 'Морський коктейль Цибуля Помідор Сир Моцарела Маслини Вершковий соус', 'simple', 'own'),
      ('Квадро Дитяча', '/demo-suncity/kvadro-dytiacha.jpg', NULL, 'Філе куряче Кукурудза Сир Чеддер Соус Вершковий', 'simple', 'own'),
      ('Квадро Fire', '/demo-suncity/kvadro-fire.jpg', NULL, 'Балик Мисливські ковбаски Кукурудза Помідор Сир Моцарела Перець Чілі Томатний соус', 'simple', 'own'),
      ('Квадро Жульєн', '/demo-suncity/kvadro-zhulien.jpg', NULL, 'Гриби Сир Чеддер Цибуля Сир Моцарела Філе куряче Помідор Вершковий соус', 'simple', 'own'),
      ('Квадро М''ясна', '/demo-suncity/kvadro-miasna.jpg', NULL, 'Салямі Бекон Мисливські ковбаски Філе куряче Сир Моцарела Помідор Томатний Соус', 'simple', 'own'),
      ('Квадро Дольче', '/demo-suncity/kvadro-dolche.jpg', NULL, 'Гриби Болгарський перець Філе куряче Кукурудза Сир Моцарела Вершковий соус', 'simple', 'own'),
      ('Квадро Алергі', '/demo-suncity/kvadro-alerhi.jpg', NULL, 'Сир Моцарела цибуля мисливські ковбаски огірок солений сир Чеддер томатний соус', 'simple', 'own'),
      ('Квадро Гавайська', '/demo-suncity/kvadro-havaiska.jpg', NULL, 'Моцарела філе куряче ананас помідор сир Чеддер томатний соус', 'simple', 'own'),
      ('Квадро Маргарита', '/demo-suncity/kvadro-marharyta.jpg', NULL, 'Соус томатний Моцарелла Томати Базилік', 'simple', 'own'),
      ('Квадро Капрічоза', '/demo-suncity/kvadro-kaprichoza.jpg', NULL, 'Соус томатний Гриби Чеддер Балик Часникова олія Моцарелла Болгарський перець', 'simple', 'own'),
      ('Квадро Прошутто', '/demo-suncity/kvadro-proshutto.jpg', NULL, 'Соус томатний Прошутто Томати Сулугуні Пармезан Чеддер Салат', 'simple', 'own'),
      ('Квадро Прошутто крудо', '/demo-suncity/kvadro-proshutto-krudo.jpg', NULL, 'Вершковий соус Томати Айсберг Філе куряче (Мариноване) Прошутто крудо Сулугуні', 'simple', 'own'),
      ('Квадро Креветка Дор-Блю', '/demo-suncity/kvadro-krevetka-dor-bliu.jpg', NULL, 'Соус шпинатний Моцарелла Оливки Креветка тигрова ДорБлю Маслини', 'simple', 'own'),
      ('Квадро Sun City', '/demo-suncity/kvadro-sun-city.jpg', NULL, 'Вершковий соус Прошутто-крудо Філе куряче(мариноване) Айсберг Цибуля Моцарела', 'simple', 'own'),
      ('Квадро Салямі', '/demo-suncity/kvadro-saliami.jpg', NULL, 'Соус томатний Салямі Чедер Томати Моцарелла', 'simple', 'own'),
      ('Квадро Тунець', '/demo-suncity/kvadro-tunets.jpg', NULL, 'Вершковий соус Тунець Томати Оливки Чеддер', 'simple', 'own'),
      ('Квадро Вулкан', '/demo-suncity/kvadro-vulkan.jpg', NULL, 'Мисливські ковбаски Чедер Моцарелла Шпинатний соус Томати', 'simple', 'own'),
      ('Квадро Чіназес', '/demo-suncity/kvadro-chinazes.jpg', NULL, 'Копчене філе Бекон Моцарела Мікс салату(можлива заміна на айсберг) Вершковий соус', 'simple', 'own'),
      ('Квадро Палермо', '/demo-suncity/kvadro-palermo.jpg', NULL, 'Прошутто ДорБлю Маслини Томати Авокадо Сир Моцарела Вершковий соус', 'simple', 'own'),
      ('Квадро Паляниця', '/demo-suncity/kvadro-palianytsia.jpg', NULL, 'Вершковий соус Моцарела ДорБлю Чедер Пармезан Часникова олія Філе мариноване', 'simple', 'own'),
      ('Квадро Карбонара', '/demo-suncity/kvadro-karbonara.jpg', NULL, 'Вершковий соус, моцарелла, бекон, балик, жовток сирий', 'simple', 'own'),
      ('Квадро Прошуто Ананас', '/demo-suncity/kvadro-proshuto-ananas.jpg', NULL, 'Ананас Соус вершковий Прошутто Бекон Чедер Моцарелла', 'simple', 'own'),
      ('Квадро Чізбургер', '/demo-suncity/kvadro-chizburher.jpg', NULL, 'Бекон Балик Томати Огірок солений Цибуля Моцарелла Сир тостовий', 'simple', 'own'),
      ('Квадро з Лисичками', '/demo-suncity/kvadro-z-lysychkamy.jpg', NULL, 'Вершковий соус Моцарела Шампіньйони Пармезан Лисички Вершки', 'simple', 'own'),
      ('Квадро Бос BBQ', '/demo-suncity/kvadro-bos-bbq.jpg', NULL, 'Соус Барбекю Балик Гриби Цибуля Помідор Сир Чедер', 'simple', 'own')
    ) AS t(name, image, description, composition, kind, mode)
  LOOP
    INSERT INTO pos_products (store_id, name, image_url, description, composition, kind, stock_mode, sellable)
    VALUES (v_store, r.name, r.image, r.description, r.composition, r.kind, r.mode, TRUE);
  END LOOP;

  INSERT INTO pos_product_tags (product_id, tag_id)
  SELECT p.id, t.id
  FROM (VALUES
      ('РОЛ ІНЬ ЯНЬ', 'Роли'),
      ('ЧОРНИЙ ДРАКОН', 'Роли'),
      ('РОЛ BLACK FIRE', 'Роли'),
      ('КАЛІФОРНІЯ ЛОСОСЬ', 'Роли'),
      ('КАЛІФОРНІЯ З ВУГРЕМ', 'Роли'),
      ('БІЛИЙ ДРАКОН', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ КУНСЕЙ', 'Роли'),
      ('КАЛІФОРНІЯ КУНСЕЙ', 'Роли'),
      ('ФУТОМАКІ КУНСЕЙ', 'Роли'),
      ('КАЛІФОРНІЯ СМАЖЕНИЙ ЛОСОСЬ', 'Роли'),
      ('КАЛІФОРНІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ ОМЛЕТ', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ КЛАСІК', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ З ТУНЦЕМ', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ З ВУГРЕМ', 'Роли'),
      ('ЧЕРВОНИЙ ДРАКОН', 'Роли'),
      ('ЗОЛОТИЙ ДРАКОН', 'Роли'),
      ('ЗЕЛЕНИЙ ДРАКОН', 'Роли'),
      ('РОЛ ВЕСЕЛКА', 'Роли'),
      ('СИР РОЯЛ DE LUX', 'Роли'),
      ('РОЛ ЧЕДДЕР', 'Роли'),
      ('РОЛ МАНГО', 'Роли'),
      ('РОЛ КРЕВЕТКА ПАНКО', 'Роли'),
      ('ФІЛАДЕЛЬФІЯ РОЯЛ DE LUX XXL', 'Роли'),
      ('РОЛ МАКІ З ОГІРКОМ', 'Роли'),
      ('РОЛ МАКІ З АВОКАДО', 'Роли'),
      ('РОЛ МАКІ З ЛОСОСЕМ', 'Роли'),
      ('РОЛ МАКІ З ТУНЦЕМ', 'Роли'),
      ('РОЛ МАКІ З ВУГРЕМ', 'Роли'),
      ('РОЛ МАКІ ЗІ СМАЖЕНИМ ЛОСОСЕМ', 'Роли'),
      ('ФУТОМАКІ З ЛОСОСЕМ ТА МАНГО', 'Роли'),
      ('ФУТОМАКІ З КОПЧЕНИМ ЛОСОСЕМ', 'Роли'),
      ('ФУТОМАКІ З ТУНЦЕМ', 'Роли'),
      ('ФУТОМАКІ З КРАБ.ПАЛОЧКОЮ', 'Роли'),
      ('ФУТОМАКІ З КРЕВЕТКОЮ', 'Роли'),
      ('ФУТОМАКІ З ВУГРЕМ', 'Роли'),
      ('ГУНКАН З КРЕВЕТКОЮ', 'Роли'),
      ('ГУНКАН З ЛОСОСЕМ', 'Роли'),
      ('ГУНКАН З ТУНЦЕМ', 'Роли'),
      ('ГУНКАН З ЧУКОЮ', 'Роли'),
      ('ГУНКАН З ІКРОЮ', 'Роли'),
      ('ГУНКАН З ВУГРЕМ', 'Роли'),
      ('ГУНКАН КУНСЕЙ', 'Роли'),
      ('РОЛ З ЧУКОЮ І ЛОСОСЕМ', 'Роли'),
      ('Ролл з чукою і креветкою', 'Роли'),
      ('Ролл з чукою і тунцем', 'Роли'),
      ('Ролл з чукою і вугрем', 'Роли'),
      ('Ролл з чукою і краб.палочкою', 'Роли'),
      ('Філадельфія з копченим лососем', 'Роли'),
      ('Каліфорнія з копченим лососем', 'Роли'),
      ('Чеддер з лососем', 'Роли'),
      ('Чеддер з тунцем', 'Роли'),
      ('Чеддер з копченим лососем', 'Роли'),
      ('Чеддер з вугрем', 'Роли'),
      ('Чеддер Манго', 'Роли'),
      ('Чеддер зі смаженим лососем', 'Роли'),
      ('Чеддер з креветкою', 'Роли'),
      ('Чеддер з крабовою палочкою', 'Роли'),
      ('Чеддер зі смаженим тунцем', 'Роли'),
      ('Каліфорнія зі смаженим тунцем', 'Роли'),
      ('Філадельфія зі смаженим тунцем', 'Роли'),
      ('Ролл з чукою і смаженим тунцем', 'Роли'),
      ('Футомакі зі смаженим тунцем', 'Роли'),
      ('Футомакі зі смаженим лососем', 'Роли'),
      ('Філадельфія смажений лосось', 'Роли'),
      ('Дракон Каліграф', 'Роли'),
      ('Тигровий дракон', 'Роли'),
      ('Нігірі лосось', 'Роли'),
      ('Нігірі вугор', 'Роли'),
      ('Нігірі креветка', 'Роли'),
      ('Нігірі Тунець', 'Роли'),
      ('Ролл від шефа', 'Роли'),
      ('Ролл Аляска', 'Роли'),
      ('Кезюрі рол', 'Роли'),
      ('Темпура з лососем', 'Роли'),
      ('Темпура з лососем', 'Темпура'),
      ('Темпура з вугрем', 'Роли'),
      ('Темпура з вугрем', 'Темпура'),
      ('Темпура з креветкою', 'Роли'),
      ('Темпура з креветкою', 'Темпура'),
      ('Темпура с краб. палочкою', 'Роли'),
      ('Темпура с краб. палочкою', 'Темпура'),
      ('Темпура з тунцем', 'Роли'),
      ('Темпура з тунцем', 'Темпура'),
      ('Рол Дог', 'Роли'),
      ('Удон смажений лосось 420г', 'ВОК'),
      ('Удон смажений тунець 420г', 'ВОК'),
      ('Удон з креветкою 400г', 'ВОК'),
      ('Веган Удон 460г', 'ВОК'),
      ('Удон з мідією 430г', 'ВОК'),
      ('Удон Морський коктейль 430г', 'ВОК'),
      ('Удон восьминіжка 430г', 'ВОК'),
      ('Сан Сет 1150г', 'Сети'),
      ('Каліфорнія сет 690г', 'Сети'),
      ('Лосось сет 890 г', 'Сети'),
      ('Сет Філадельфія XXL 1320 г', 'Сети'),
      ('Тріо сет 680 г', 'Сети'),
      ('Сет Преміум 1660г', 'Сети'),
      ('Дракон СЕТ 830г', 'Сети'),
      ('Сет Сирний 1040г', 'Сети'),
      ('Сет Філадельфія MAXI', 'Сети'),
      ('Сет Хіяши 760г', 'Сети'),
      ('Сет Драконів MAX', 'Сети'),
      ('Бургер з запеченим філе', 'Фаст-Фуд'),
      ('Бургер з запеченим філе', 'Бургери'),
      ('Бургер з запеченим філе та сиром', 'Фаст-Фуд'),
      ('Бургер з запеченим філе та сиром', 'Бургери'),
      ('Бургер з запеченим філе та подвійним сиром', 'Фаст-Фуд'),
      ('Бургер з запеченим філе та подвійним сиром', 'Бургери'),
      ('Шаурма', 'Шаурма'),
      ('Шаурма', 'Фаст-Фуд'),
      ('Шаурма з сиром', 'Фаст-Фуд'),
      ('Шаурма з сиром', 'Шаурма'),
      ('Креветка Панко 10 шт', 'Темпура'),
      ('Хот дог в лаваші з 2 сосисками', 'Хот-Дог'),
      ('Хот дог в лаваші з 2 сосисками', 'Фаст-Фуд'),
      ('Хот дог французький', 'Хот-Дог'),
      ('Хот дог французький', 'Фаст-Фуд'),
      ('Хот дог американский', 'Хот-Дог'),
      ('Хот дог американский', 'Фаст-Фуд'),
      ('Бургер з курячою котлетою', 'Фаст-Фуд'),
      ('Бургер з курячою котлетою', 'Бургери'),
      ('Бургер з курячою котлетою та сиром', 'Фаст-Фуд'),
      ('Бургер з курячою котлетою та сиром', 'Бургери'),
      ('Бургер з курячою котлетою та подвійним сиром', 'Фаст-Фуд'),
      ('Бургер з курячою котлетою та подвійним сиром', 'Бургери'),
      ('Бургер з яловичою котлетою', 'Фаст-Фуд'),
      ('Бургер з яловичою котлетою', 'Бургери'),
      ('Бургер Sun City з яловичою котлетою', 'Фаст-Фуд'),
      ('Бургер Sun City з яловичою котлетою', 'Бургери'),
      ('Бургер Sun City з курячою котлетою', 'Фаст-Фуд'),
      ('Бургер Sun City з курячою котлетою', 'Бургери'),
      ('Бургер з яловичою котлетою та сиром', 'Фаст-Фуд'),
      ('Бургер з яловичою котлетою та сиром', 'Бургери'),
      ('Бургер з яловичою котлетою та подвійним сиром', 'Фаст-Фуд'),
      ('Бургер з яловичою котлетою та подвійним сиром', 'Бургери'),
      ('Суши бургер з лососем 330г', 'Бургери'),
      ('Суши бургер з креветкою 330г', 'Бургери'),
      ('Black суші бургер', 'Бургери'),
      ('Преміум ROYAL сет від шефа 3000г', 'Сети'),
      ('Темпура XXL сет 1300г', 'Сети'),
      ('Тріо темпура сет 780г', 'Сети'),
      ('Міх сет 990 г', 'Сети'),
      ('Класичний сет 1035г', 'Сети'),
      ('Гурман сет 875 г', 'Сети'),
      ('Дабл суші сет 510г', 'Сети'),
      ('Фаворит сет 800 г', 'Сети'),
      ('Креветка 4х сет 880 г', 'Сети'),
      ('Лосось 4х сет 845г', 'Сети'),
      ('Вугор 4х сет 875 г', 'Сети'),
      ('Тунец 4х сет 875 г', 'Сети'),
      ('Люкс сет 2425 г', 'Сети'),
      ('Курка', 'Гриль'),
      ('Крило', 'Гриль'),
      ('Бедро', 'Гриль'),
      ('Нагетси', 'Фаст-Фуд'),
      ('Картопля Фрі', 'Фаст-Фуд'),
      ('Картопля по-селянськи', 'Фаст-Фуд'),
      ('Картопля по-селянськи', 'Пропозиція тижня'),
      ('Double Meet', 'Піцца'),
      ('Double Fish', 'Піцца'),
      ('4 сира', 'Піцца'),
      ('Веган', 'Піцца'),
      ('Пепероні', 'Піцца'),
      ('Філадельфія', 'Піцца'),
      ('Маринара', 'Піцца'),
      ('Дитяча', 'Піцца'),
      ('Fire', 'Піцца'),
      ('Double Chicken', 'Піцца'),
      ('Жульєн', 'Піцца'),
      ('Double Cheese', 'Піцца'),
      ('М''ясна', 'Піцца'),
      ('Дольче', 'Піцца'),
      ('Чотири сезона', 'Піцца'),
      ('Алегрі', 'Піцца'),
      ('Гавайська', 'Піцца'),
      ('Шаурма по-домашньому з ковбаскою', 'Шаурма'),
      ('Деруни', 'Фаст-Фуд'),
      ('Деруни', 'Меню'),
      ('Картопляні кульки', 'Фаст-Фуд'),
      ('Цибулеві кільця', 'Фаст-Фуд'),
      ('Крильця Sun City', 'Фаст-Фуд'),
      ('Стейк меню', 'Меню'),
      ('Міні ланч бокс', 'Меню'),
      ('Маргарита', 'Піцца'),
      ('Капрічоза', 'Піцца'),
      ('Прошутто', 'Піцца'),
      ('Прошутто крудо', 'Піцца'),
      ('Креветка Дор-Блю', 'Піцца'),
      ('Sun City', 'Піцца'),
      ('Салямі', 'Піцца'),
      ('Тунець', 'Піцца'),
      ('Вулкан', 'Піцца'),
      ('Чіназес', 'Піцца'),
      ('Палермо', 'Піцца'),
      ('Рол Укроп з комо', 'Роли'),
      ('Рол Укроп з комо', 'Українські роли'),
      ('Рол Укроп з філадельфією', 'Роли'),
      ('Рол Укроп з філадельфією', 'Українські роли'),
      ('Рол Мехіко', 'Роли'),
      ('Рол grill cheese з лососем', 'Роли'),
      ('Рол Тоторі', 'Роли'),
      ('Рол Тоторі', 'Пропозиція тижня'),
      ('Рол чеддер з копченою куркою', 'Роли'),
      ('Рол лосось Махі', 'Роли'),
      ('Рол Тунець Махі 260г', 'Роли'),
      ('Рол Вугор Махі 280г', 'Роли'),
      ('Рол Креветка Махі 280г', 'Роли'),
      ('Рол Копчений лосось Махі 260г', 'Роли'),
      ('Рол філадельфія Cheese', 'Роли'),
      ('Футомак з коп. куркою та болг.перцем 260г', 'Роли'),
      ('Рол каліфорнія Chicken 210г', 'Роли'),
      ('Рол Тропік', 'Роли'),
      ('Рол Фрутіс', 'Роли'),
      ('Рол Спайсі Блек', 'Роли'),
      ('Кето Рол', 'Роли'),
      ('Салат з чукою лососем та авокадо', 'Салати'),
      ('Салат з чукою лососем і манго', 'Салати'),
      ('Салат з чукою і тунцем', 'Салати'),
      ('Салат з чукою і креветкою', 'Салати'),
      ('Салат з чукою і копченим лососем', 'Салати'),
      ('Салат з чукою і копченим лососем', 'Пропозиція тижня'),
      ('Салат з чукою і смаженим лососем', 'Салати'),
      ('Темпура кунсей', 'Темпура'),
      ('Сет філадельфія класік', 'Сети'),
      ('Рол чікен філадельфія', 'Роли'),
      ('Суші пончик з креветкою', 'Суші пончик'),
      ('Суші пончик з лососем', 'Суші пончик'),
      ('Суші пончик Чеддер', 'Суші пончик'),
      ('Суші пончик з вугрем', 'Суші пончик'),
      ('Суши пончик з тунцем', 'Суші пончик'),
      ('Кальмар', 'Фаст-Фуд'),
      ('Паляниця', 'Піцца'),
      ('Хот дог в лаваші з 3 сосисками', 'Хот-Дог'),
      ('Карбонара', 'Піцца'),
      ('Стейк лосось меню', 'Меню'),
      ('Фрі бокс', 'Меню'),
      ('Фрі бокс XXL', 'Фаст-Фуд'),
      ('Сет Макі', 'Сети'),
      ('Сет Драконів Махі ХХЛ', 'Сети'),
      ('Філадельфія кунсей сет', 'Сети'),
      ('Прошуто Ананас', 'Піцца'),
      ('Чізбургер', 'Піцца'),
      ('Піца з лисичками', 'Піцца'),
      ('Діпи картопляні', 'Фаст-Фуд'),
      ('Сирні палички', 'Фаст-Фуд'),
      ('Фрі меню', 'Меню'),
      ('Меню по-селянські', 'Меню'),
      ('Double бургер', 'Бургери'),
      ('Сет Футомакі', 'Сети'),
      ('Темпура фірмова', 'Темпура'),
      ('Суші бургер Кунсей', 'Бургери'),
      ('Sun Fri', 'Піцца'),
      ('Шаурма по Царськи', 'Шаурма'),
      ('Шаурма по Царськи', 'Фаст-Фуд'),
      ('Шаурма Фрі', 'Шаурма'),
      ('Шаурма Фрі', 'Фаст-Фуд'),
      ('Піца Ягідна', 'Піцца'),
      ('Піца Ягідна', 'Пропозиція тижня'),
      ('Піца Фісташкова', 'Піцца'),
      ('Піца Фруктова', 'Піцца'),
      ('Бос BBQ', 'Піцца'),
      ('BBQ Gold', 'Піцца'),
      ('Бургер гриль', 'Бургери'),
      ('Квадро 4 сира', 'Піцца'),
      ('Квадро Веган', 'Піцца'),
      ('Квадро Пепероні', 'Піцца'),
      ('Квадро Філадельфія', 'Піцца'),
      ('Квадро Маринара', 'Піцца'),
      ('Квадро Дитяча', 'Піцца'),
      ('Квадро Fire', 'Піцца'),
      ('Квадро Жульєн', 'Піцца'),
      ('Квадро М''ясна', 'Піцца'),
      ('Квадро Дольче', 'Піцца'),
      ('Квадро Алергі', 'Піцца'),
      ('Квадро Гавайська', 'Піцца'),
      ('Квадро Маргарита', 'Піцца'),
      ('Квадро Капрічоза', 'Піцца'),
      ('Квадро Прошутто', 'Піцца'),
      ('Квадро Прошутто крудо', 'Піцца'),
      ('Квадро Креветка Дор-Блю', 'Піцца'),
      ('Квадро Sun City', 'Піцца'),
      ('Квадро Салямі', 'Піцца'),
      ('Квадро Тунець', 'Піцца'),
      ('Квадро Вулкан', 'Піцца'),
      ('Квадро Чіназес', 'Піцца'),
      ('Квадро Палермо', 'Піцца'),
      ('Квадро Паляниця', 'Піцца'),
      ('Квадро Карбонара', 'Піцца'),
      ('Квадро Прошуто Ананас', 'Піцца'),
      ('Квадро Чізбургер', 'Піцца'),
      ('Квадро з Лисичками', 'Піцца'),
      ('Квадро Бос BBQ', 'Піцца')
  ) AS x(product, tag)
  JOIN pos_products p ON p.store_id = v_store AND p.name = x.product
  JOIN pos_tags t ON t.store_id = v_store AND t.name = x.tag;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows <> 294 THEN
    RAISE EXCEPTION 'demo-suncity: % of 294 dish categories matched', v_rows;
  END IF;

  -- One row per size. The caption is the café rule (`cafe.ts` labelOf: the
  -- size, or nothing), written out because SQL cannot call it;
  -- `pos.demo-suncity.test.ts` re-derives every one. Cost 0 is «not known».
  FOR r IN
    SELECT * FROM (VALUES
      ('РОЛ ІНЬ ЯНЬ', NULL, 27500, 50),
      ('ЧОРНИЙ ДРАКОН', NULL, 32500, 50),
      ('РОЛ BLACK FIRE', NULL, 28000, 50),
      ('КАЛІФОРНІЯ ЛОСОСЬ', NULL, 25000, 50),
      ('КАЛІФОРНІЯ З ВУГРЕМ', NULL, 25000, 50),
      ('БІЛИЙ ДРАКОН', NULL, 29500, 50),
      ('ФІЛАДЕЛЬФІЯ КУНСЕЙ', NULL, 27000, 50),
      ('КАЛІФОРНІЯ КУНСЕЙ', NULL, 26000, 50),
      ('ФУТОМАКІ КУНСЕЙ', NULL, 22000, 50),
      ('КАЛІФОРНІЯ СМАЖЕНИЙ ЛОСОСЬ', NULL, 24500, 50),
      ('КАЛІФОРНІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', NULL, 23000, 50),
      ('ФІЛАДЕЛЬФІЯ ОМЛЕТ', NULL, 23000, 50),
      ('ФІЛАДЕЛЬФІЯ КЛАСІК', NULL, 25000, 50),
      ('ФІЛАДЕЛЬФІЯ З ТУНЦЕМ', NULL, 25500, 50),
      ('ФІЛАДЕЛЬФІЯ З ТИГРОВОЮ КРЕВЕТКОЮ', NULL, 26000, 50),
      ('ФІЛАДЕЛЬФІЯ З ВУГРЕМ', NULL, 24000, 50),
      ('ЧЕРВОНИЙ ДРАКОН', NULL, 28500, 50),
      ('ЗОЛОТИЙ ДРАКОН', NULL, 29000, 50),
      ('ЗЕЛЕНИЙ ДРАКОН', NULL, 28000, 50),
      ('РОЛ ВЕСЕЛКА', NULL, 25000, 50),
      ('СИР РОЯЛ DE LUX', NULL, 24000, 50),
      ('РОЛ ЧЕДДЕР', NULL, 21000, 50),
      ('РОЛ МАНГО', NULL, 22500, 50),
      ('РОЛ КРЕВЕТКА ПАНКО', NULL, 24000, 50),
      ('ФІЛАДЕЛЬФІЯ РОЯЛ DE LUX XXL', NULL, 27000, 50),
      ('РОЛ МАКІ З ОГІРКОМ', NULL, 10000, 50),
      ('РОЛ МАКІ З АВОКАДО', NULL, 11000, 50),
      ('РОЛ МАКІ З ЛОСОСЕМ', NULL, 14000, 50),
      ('РОЛ МАКІ З ТУНЦЕМ', NULL, 14000, 50),
      ('РОЛ МАКІ З ВУГРЕМ', NULL, 15000, 50),
      ('РОЛ МАКІ ЗІ СМАЖЕНИМ ЛОСОСЕМ', NULL, 15500, 50),
      ('ФУТОМАКІ З ЛОСОСЕМ ТА МАНГО', NULL, 22500, 50),
      ('ФУТОМАКІ З КОПЧЕНИМ ЛОСОСЕМ', NULL, 23000, 50),
      ('ФУТОМАКІ З ТУНЦЕМ', NULL, 22500, 50),
      ('ФУТОМАКІ З КРАБ.ПАЛОЧКОЮ', NULL, 19500, 50),
      ('ФУТОМАКІ З КРЕВЕТКОЮ', NULL, 23000, 50),
      ('ФУТОМАКІ З ВУГРЕМ', NULL, 21000, 50),
      ('ГУНКАН З КРЕВЕТКОЮ', NULL, 7500, 50),
      ('ГУНКАН З ЛОСОСЕМ', NULL, 8000, 50),
      ('ГУНКАН З ТУНЦЕМ', NULL, 8000, 50),
      ('ГУНКАН З ЧУКОЮ', NULL, 6500, 50),
      ('ГУНКАН З ІКРОЮ', NULL, 7000, 50),
      ('ГУНКАН З ВУГРЕМ', NULL, 8000, 50),
      ('ГУНКАН КУНСЕЙ', NULL, 8000, 50),
      ('РОЛ З ЧУКОЮ І ЛОСОСЕМ', NULL, 21500, 50),
      ('Ролл з чукою і креветкою', NULL, 21000, 50),
      ('Ролл з чукою і тунцем', NULL, 21500, 50),
      ('Ролл з чукою і вугрем', NULL, 23000, 50),
      ('Ролл з чукою і краб.палочкою', NULL, 20000, 50),
      ('Філадельфія з копченим лососем', NULL, 26000, 50),
      ('Каліфорнія з копченим лососем', NULL, 21000, 50),
      ('Чеддер з лососем', NULL, 23000, 50),
      ('Чеддер з тунцем', NULL, 22500, 50),
      ('Чеддер з копченим лососем', NULL, 23000, 50),
      ('Чеддер з вугрем', NULL, 26500, 50),
      ('Чеддер Манго', NULL, 23000, 50),
      ('Чеддер зі смаженим лососем', NULL, 24000, 50),
      ('Чеддер з креветкою', NULL, 25000, 50),
      ('Чеддер з крабовою палочкою', NULL, 20500, 50),
      ('Чеддер зі смаженим тунцем', NULL, 25500, 50),
      ('Каліфорнія зі смаженим тунцем', NULL, 24500, 50),
      ('Філадельфія зі смаженим тунцем', NULL, 23000, 50),
      ('Ролл з чукою і смаженим тунцем', NULL, 23000, 50),
      ('Футомакі зі смаженим тунцем', NULL, 21000, 50),
      ('Футомакі зі смаженим лососем', NULL, 23000, 50),
      ('Філадельфія смажений лосось', NULL, 24500, 50),
      ('Дракон Каліграф', NULL, 27000, 50),
      ('Тигровий дракон', NULL, 29500, 50),
      ('Нігірі лосось', NULL, 8000, 50),
      ('Нігірі вугор', NULL, 8500, 50),
      ('Нігірі креветка', NULL, 8000, 50),
      ('Нігірі Тунець', NULL, 7500, 50),
      ('Ролл від шефа', NULL, 26000, 50),
      ('Ролл Аляска', NULL, 24000, 50),
      ('Кезюрі рол', NULL, 27000, 50),
      ('Темпура з лососем', NULL, 25000, 50),
      ('Темпура з вугрем', NULL, 27000, 50),
      ('Темпура з креветкою', NULL, 28000, 50),
      ('Темпура с краб. палочкою', NULL, 23000, 50),
      ('Темпура з тунцем', NULL, 26000, 50),
      ('Рол Дог', NULL, 26500, 50),
      ('Удон смажений лосось 420г', NULL, 27000, 50),
      ('Удон смажений тунець 420г', NULL, 26000, 50),
      ('Удон з креветкою 400г', NULL, 26500, 50),
      ('Веган Удон 460г', NULL, 20000, 50),
      ('Удон з мідією 430г', NULL, 22000, 50),
      ('Удон Морський коктейль 430г', NULL, 23000, 50),
      ('Удон восьминіжка 430г', NULL, 25500, 50),
      ('Сан Сет 1150г', NULL, 108000, 50),
      ('Каліфорнія сет 690г', NULL, 71000, 50),
      ('Лосось сет 890 г', NULL, 83000, 50),
      ('Сет Філадельфія XXL 1320 г', NULL, 120500, 50),
      ('Тріо сет 680 г', NULL, 71000, 50),
      ('Сет Преміум 1660г', NULL, 165000, 50),
      ('Дракон СЕТ 830г', NULL, 84000, 50),
      ('Сет Сирний 1040г', NULL, 89500, 50),
      ('Сет Філадельфія MAXI', NULL, 125000, 50),
      ('Сет Хіяши 760г', NULL, 62500, 50),
      ('Сет Драконів MAX', NULL, 140500, 50),
      ('Бургер з запеченим філе', NULL, 10000, 50),
      ('Бургер з запеченим філе та сиром', NULL, 11000, 50),
      ('Бургер з запеченим філе та подвійним сиром', NULL, 12000, 50),
      ('Шаурма', NULL, 12000, 50),
      ('Шаурма з сиром', NULL, 14000, 50),
      ('Креветка Панко 10 шт', NULL, 39000, 50),
      ('Хот дог в лаваші з 2 сосисками', NULL, 12000, 50),
      ('Хот дог французький', NULL, 8000, 50),
      ('Хот дог американский', NULL, 8000, 50),
      ('Бургер з курячою котлетою', NULL, 10000, 50),
      ('Бургер з курячою котлетою та сиром', NULL, 11000, 50),
      ('Бургер з курячою котлетою та подвійним сиром', NULL, 12000, 50),
      ('Бургер з яловичою котлетою', NULL, 10000, 50),
      ('Бургер Sun City з яловичою котлетою', NULL, 14000, 50),
      ('Бургер Sun City з курячою котлетою', NULL, 14000, 50),
      ('Бургер з яловичою котлетою та сиром', NULL, 11000, 50),
      ('Бургер з яловичою котлетою та подвійним сиром', NULL, 12000, 50),
      ('Суши бургер з лососем 330г', NULL, 27000, 50),
      ('Суши бургер з креветкою 330г', NULL, 28000, 50),
      ('Black суші бургер', NULL, 32000, 50),
      ('Преміум ROYAL сет від шефа 3000г', NULL, 337700, 50),
      ('Темпура XXL сет 1300г', NULL, 127500, 50),
      ('Тріо темпура сет 780г', NULL, 77500, 50),
      ('Міх сет 990 г', NULL, 96500, 50),
      ('Класичний сет 1035г', NULL, 97500, 50),
      ('Гурман сет 875 г', NULL, 117500, 50),
      ('Дабл суші сет 510г', NULL, 73000, 50),
      ('Фаворит сет 800 г', NULL, 76000, 50),
      ('Креветка 4х сет 880 г', NULL, 85500, 50),
      ('Лосось 4х сет 845г', NULL, 85000, 50),
      ('Вугор 4х сет 875 г', NULL, 89000, 50),
      ('Тунец 4х сет 875 г', NULL, 83500, 50),
      ('Люкс сет 2425 г', NULL, 239000, 50),
      ('Курка', NULL, 23500, 50),
      ('Крило', NULL, 23500, 50),
      ('Бедро', NULL, 28000, 50),
      ('Нагетси', NULL, 7000, 50),
      ('Картопля Фрі', NULL, 7000, 50),
      ('Картопля по-селянськи', NULL, 7000, 50),
      ('Double Meet', '30 см', 23000, 50),
      ('Double Meet', '50 см', 41000, 50),
      ('Double Fish', '30 см', 36000, 50),
      ('Double Fish', '50 см', 58000, 50),
      ('4 сира', '30 см', 29000, 50),
      ('4 сира', '50 см', 41000, 50),
      ('Веган', '30 см', 21000, 50),
      ('Веган', '50 см', 35000, 50),
      ('Пепероні', '30 см', 27000, 50),
      ('Пепероні', '50 см', 43000, 50),
      ('Філадельфія', '30 см', 47000, 50),
      ('Філадельфія', '50 см', 69500, 50),
      ('Маринара', '30 см', 29000, 50),
      ('Маринара', '50 см', 50000, 50),
      ('Дитяча', '30 см', 22000, 50),
      ('Дитяча', '50 см', 38000, 50),
      ('Fire', '30 см', 22000, 50),
      ('Fire', '50 см', 39000, 50),
      ('Double Chicken', '30 см', 25000, 50),
      ('Double Chicken', '50 см', 39000, 50),
      ('Жульєн', '30 см', 23000, 50),
      ('Жульєн', '50 см', 39000, 50),
      ('Double Cheese', '30 см', 23000, 50),
      ('Double Cheese', '50 см', 42000, 50),
      ('М''ясна', '30 см', 24000, 50),
      ('М''ясна', '50 см', 41000, 50),
      ('Дольче', '30 см', 24000, 50),
      ('Дольче', '50 см', 43000, 50),
      ('Чотири сезона', '30 см', 25000, 50),
      ('Чотири сезона', '50 см', 45000, 50),
      ('Алегрі', '30 см', 26000, 50),
      ('Алегрі', '50 см', 45000, 50),
      ('Гавайська', '30 см', 27000, 50),
      ('Гавайська', '50 см', 48000, 50),
      ('Шаурма по-домашньому з ковбаскою', NULL, 14000, 50),
      ('Деруни', NULL, 10000, 50),
      ('Картопляні кульки', NULL, 8000, 50),
      ('Цибулеві кільця', NULL, 9000, 50),
      ('Крильця Sun City', NULL, 21000, 50),
      ('Стейк меню', NULL, 33500, 50),
      ('Міні ланч бокс', NULL, 25000, 50),
      ('Маргарита', '30 см', 21000, 50),
      ('Маргарита', '50 см', 37000, 50),
      ('Капрічоза', '30 см', 23000, 50),
      ('Капрічоза', '50 см', 39500, 50),
      ('Прошутто', '30 см', 27000, 50),
      ('Прошутто', '50 см', 47000, 50),
      ('Прошутто крудо', '30 см', 27000, 50),
      ('Прошутто крудо', '50 см', 49000, 50),
      ('Креветка Дор-Блю', '30 см', 27000, 50),
      ('Креветка Дор-Блю', '50 см', 49000, 50),
      ('Sun City', '30 см', 31000, 50),
      ('Sun City', '50 см', 53000, 50),
      ('Салямі', '30 см', 23500, 50),
      ('Салямі', '50 см', 41000, 50),
      ('Тунець', '30 см', 29000, 50),
      ('Тунець', '50 см', 51500, 50),
      ('Вулкан', '30 см', 23500, 50),
      ('Вулкан', '50 см', 37000, 50),
      ('Чіназес', '30 см', 23000, 50),
      ('Чіназес', '50 см', 39000, 50),
      ('Палермо', '30 см', 25000, 50),
      ('Палермо', '50 см', 44000, 50),
      ('Рол Укроп з комо', NULL, 19000, 50),
      ('Рол Укроп з філадельфією', NULL, 19000, 50),
      ('Рол Мехіко', NULL, 26000, 50),
      ('Рол grill cheese з лососем', NULL, 27500, 50),
      ('Рол Тоторі', NULL, 24500, 50),
      ('Рол чеддер з копченою куркою', NULL, 23000, 50),
      ('Рол лосось Махі', NULL, 30000, 50),
      ('Рол Тунець Махі 260г', NULL, 29000, 50),
      ('Рол Вугор Махі 280г', NULL, 33000, 50),
      ('Рол Креветка Махі 280г', NULL, 32000, 50),
      ('Рол Копчений лосось Махі 260г', NULL, 32000, 50),
      ('Рол філадельфія Cheese', NULL, 33500, 50),
      ('Футомак з коп. куркою та болг.перцем 260г', NULL, 19500, 50),
      ('Рол каліфорнія Chicken 210г', NULL, 20500, 50),
      ('Рол Тропік', NULL, 26000, 50),
      ('Рол Фрутіс', NULL, 27500, 50),
      ('Рол Спайсі Блек', NULL, 19500, 50),
      ('Кето Рол', NULL, 49500, 50),
      ('Салат з чукою лососем та авокадо', NULL, 26500, 50),
      ('Салат з чукою лососем і манго', NULL, 26000, 50),
      ('Салат з чукою і тунцем', NULL, 27500, 50),
      ('Салат з чукою і креветкою', NULL, 23500, 50),
      ('Салат з чукою і копченим лососем', NULL, 25500, 50),
      ('Салат з чукою і смаженим лососем', NULL, 25500, 50),
      ('Темпура кунсей', NULL, 25500, 50),
      ('Сет філадельфія класік', NULL, 70500, 50),
      ('Рол чікен філадельфія', NULL, 22000, 50),
      ('Суші пончик з креветкою', NULL, 29500, 50),
      ('Суші пончик з лососем', NULL, 28000, 50),
      ('Суші пончик Чеддер', NULL, 25500, 50),
      ('Суші пончик з вугрем', NULL, 30000, 50),
      ('Суши пончик з тунцем', NULL, 27000, 50),
      ('Кальмар', NULL, 22000, 50),
      ('Паляниця', '30 см', 26000, 50),
      ('Паляниця', '50 см', 43000, 50),
      ('Хот дог в лаваші з 3 сосисками', NULL, 14000, 50),
      ('Карбонара', '30 см', 24000, 50),
      ('Карбонара', '50 см', 39000, 50),
      ('Стейк лосось меню', NULL, 56000, 50),
      ('Фрі бокс', NULL, 24000, 50),
      ('Фрі бокс XXL', NULL, 87000, 50),
      ('Сет Макі', NULL, 72000, 50),
      ('Сет Драконів Махі ХХЛ', NULL, 170000, 50),
      ('Філадельфія кунсей сет', NULL, 74500, 50),
      ('Прошуто Ананас', '30 см', 31000, 50),
      ('Прошуто Ананас', '50 см', 47000, 50),
      ('Чізбургер', '30 см', 27000, 50),
      ('Чізбургер', '50 см', 46000, 50),
      ('Піца з лисичками', '30 см', 27000, 50),
      ('Піца з лисичками', '50 см', 44000, 50),
      ('Діпи картопляні', NULL, 8000, 50),
      ('Сирні палички', NULL, 10000, 50),
      ('Фрі меню', NULL, 13000, 50),
      ('Меню по-селянські', NULL, 13000, 50),
      ('Double бургер', NULL, 18000, 50),
      ('Сет Футомакі', NULL, 86500, 50),
      ('Темпура фірмова', NULL, 26500, 50),
      ('Суші бургер Кунсей', NULL, 28000, 50),
      ('Sun Fri', '30 см', 26500, 50),
      ('Шаурма по Царськи', NULL, 19000, 50),
      ('Шаурма Фрі', NULL, 16000, 50),
      ('Піца Ягідна', '30 см', 38000, 50),
      ('Піца Фісташкова', '30 см', 36000, 50),
      ('Піца Фруктова', '30 см', 37000, 50),
      ('Бос BBQ', '30 см', 37000, 50),
      ('Бос BBQ', '50 см', 49000, 50),
      ('BBQ Gold', '30 см', 38000, 50),
      ('BBQ Gold', '50 см', 49500, 50),
      ('Бургер гриль', NULL, 16000, 50),
      ('Квадро 4 сира', '10х20 см', 14500, 50),
      ('Квадро Веган', '10х20 см', 11000, 50),
      ('Квадро Пепероні', '10х20 см', 13500, 50),
      ('Квадро Філадельфія', '10х20 см', 23500, 50),
      ('Квадро Маринара', '10х20 см', 14500, 50),
      ('Квадро Дитяча', '10х20 см', 11000, 50),
      ('Квадро Fire', '10х20 см', 11000, 50),
      ('Квадро Жульєн', '10х20 см', 13000, 50),
      ('Квадро М''ясна', '10х20 см', 12000, 50),
      ('Квадро Дольче', '10х20 см', 12000, 50),
      ('Квадро Алергі', '10х20 см', 13000, 50),
      ('Квадро Гавайська', '10х20 см', 13000, 50),
      ('Квадро Маргарита', '10х20 см', 11000, 50),
      ('Квадро Капрічоза', '10х20 см', 12000, 50),
      ('Квадро Прошутто', '10х20 см', 13000, 50),
      ('Квадро Прошутто крудо', '10х20 см', 13500, 50),
      ('Квадро Креветка Дор-Блю', '10х20 см', 13500, 50),
      ('Квадро Sun City', '10х20 см', 15500, 50),
      ('Квадро Салямі', '10х20 см', 11500, 50),
      ('Квадро Тунець', '10х20 см', 14500, 50),
      ('Квадро Вулкан', '10х20 см', 12000, 50),
      ('Квадро Чіназес', '10х20 см', 11000, 50),
      ('Квадро Палермо', '10х20 см', 12500, 50),
      ('Квадро Паляниця', '10х20 см', 13000, 50),
      ('Квадро Карбонара', '10х20 см', 12000, 50),
      ('Квадро Прошуто Ананас', '10х20 см', 15500, 50),
      ('Квадро Чізбургер', '10х20 см', 13500, 50),
      ('Квадро з Лисичками', '10х20 см', 13500, 50),
      ('Квадро Бос BBQ', '10х20 см', 16000, 50)
    ) AS t(product, size, price, qty)
  LOOP
    SELECT id INTO v_prod FROM pos_products WHERE store_id = v_store AND name = r.product;
    INSERT INTO pos_variants (store_id, product_id, attributes, label, unit, price_cents, cost_cents)
    VALUES (
      v_store, v_prod,
      CASE WHEN r.size IS NULL THEN '{}'::jsonb ELSE jsonb_build_object('size', r.size) END,
      COALESCE(r.size, ''),
      'шт', r.price, 0
    )
    RETURNING id INTO v_variant;
    INSERT INTO pos_stock (variant_id, store_id, quantity) VALUES (v_variant, v_store, r.qty);
    IF r.qty > 0 THEN
      INSERT INTO pos_stock_movements (store_id, variant_id, delta, reason, note)
      VALUES (v_store, v_variant, r.qty, 'seed', 'Initial stock');
    END IF;
  END LOOP;

  -- ── Pizza questions ─────────────────────────────────────────────────────
  -- One crust and one sauce, both optional, as on the site. The crust costs
  -- more on the 50 см pizza: `label_deltas` (066) holds that size's price.
  FOR r IN
    SELECT * FROM (VALUES
      ('Бортики', 0, 1, 10),
      ('Соус', 0, 1, 20)
    ) AS t(name, min_sel, max_sel, ord)
  LOOP
    INSERT INTO pos_modifier_groups (store_id, name, min_select, max_select, sort_order)
    VALUES (v_store, r.name, r.min_sel, r.max_sel, r.ord);
  END LOOP;

  FOR c IN
    SELECT * FROM (VALUES
      ('Бортики', 'Філадельфія', 8000, '[{"label":"50 см","price_delta_cents":15000}]', 0),
      ('Бортики', 'Моцарелла', 5000, '[{"label":"50 см","price_delta_cents":8000}]', 1),
      ('Бортики', 'Кунжутний', 1000, '[{"label":"50 см","price_delta_cents":1500}]', 2),
      ('Соус', 'Бургер', 3000, '[]', 0),
      ('Соус', 'Гострий', 3000, '[]', 1),
      ('Соус', 'Спайс', 3000, '[]', 2),
      ('Соус', 'Часникова олія', 3000, '[]', 3)
    ) AS t(grp, answer, delta, label_deltas, ord)
  LOOP
    SELECT id INTO v_group FROM pos_modifier_groups WHERE store_id = v_store AND name = c.grp;
    INSERT INTO pos_modifiers (store_id, group_id, name, price_delta_cents, label_deltas, sort_order)
    VALUES (v_store, v_group, c.answer, c.delta, c.label_deltas::jsonb, c.ord);
  END LOOP;

  INSERT INTO pos_product_modifier_groups (store_id, product_id, group_id, sort_order)
  SELECT v_store, p.id, g.id, x.ord
  FROM (VALUES
      ('Double Meet', 'Бортики', 0),
      ('Double Meet', 'Соус', 1),
      ('Double Fish', 'Бортики', 0),
      ('Double Fish', 'Соус', 1),
      ('4 сира', 'Бортики', 0),
      ('4 сира', 'Соус', 1),
      ('Веган', 'Бортики', 0),
      ('Веган', 'Соус', 1),
      ('Пепероні', 'Бортики', 0),
      ('Пепероні', 'Соус', 1),
      ('Філадельфія', 'Бортики', 0),
      ('Філадельфія', 'Соус', 1),
      ('Маринара', 'Бортики', 0),
      ('Маринара', 'Соус', 1),
      ('Дитяча', 'Бортики', 0),
      ('Дитяча', 'Соус', 1),
      ('Fire', 'Бортики', 0),
      ('Fire', 'Соус', 1),
      ('Double Chicken', 'Бортики', 0),
      ('Double Chicken', 'Соус', 1),
      ('Жульєн', 'Бортики', 0),
      ('Жульєн', 'Соус', 1),
      ('Double Cheese', 'Бортики', 0),
      ('Double Cheese', 'Соус', 1),
      ('М''ясна', 'Бортики', 0),
      ('М''ясна', 'Соус', 1),
      ('Дольче', 'Бортики', 0),
      ('Дольче', 'Соус', 1),
      ('Чотири сезона', 'Бортики', 0),
      ('Чотири сезона', 'Соус', 1),
      ('Алегрі', 'Бортики', 0),
      ('Алегрі', 'Соус', 1),
      ('Гавайська', 'Бортики', 0),
      ('Гавайська', 'Соус', 1),
      ('Маргарита', 'Бортики', 0),
      ('Маргарита', 'Соус', 1),
      ('Капрічоза', 'Бортики', 0),
      ('Капрічоза', 'Соус', 1),
      ('Прошутто', 'Бортики', 0),
      ('Прошутто', 'Соус', 1),
      ('Прошутто крудо', 'Бортики', 0),
      ('Прошутто крудо', 'Соус', 1),
      ('Креветка Дор-Блю', 'Бортики', 0),
      ('Креветка Дор-Блю', 'Соус', 1),
      ('Sun City', 'Бортики', 0),
      ('Sun City', 'Соус', 1),
      ('Салямі', 'Бортики', 0),
      ('Салямі', 'Соус', 1),
      ('Тунець', 'Бортики', 0),
      ('Тунець', 'Соус', 1),
      ('Вулкан', 'Бортики', 0),
      ('Вулкан', 'Соус', 1),
      ('Чіназес', 'Бортики', 0),
      ('Чіназес', 'Соус', 1),
      ('Палермо', 'Бортики', 0),
      ('Палермо', 'Соус', 1),
      ('Паляниця', 'Бортики', 0),
      ('Паляниця', 'Соус', 1),
      ('Карбонара', 'Бортики', 0),
      ('Карбонара', 'Соус', 1),
      ('Прошуто Ананас', 'Бортики', 0),
      ('Прошуто Ананас', 'Соус', 1),
      ('Чізбургер', 'Бортики', 0),
      ('Чізбургер', 'Соус', 1),
      ('Піца з лисичками', 'Бортики', 0),
      ('Піца з лисичками', 'Соус', 1),
      ('Бос BBQ', 'Бортики', 0),
      ('Бос BBQ', 'Соус', 1),
      ('BBQ Gold', 'Бортики', 0),
      ('BBQ Gold', 'Соус', 1)
  ) AS x(product, grp, ord)
  JOIN pos_products p ON p.store_id = v_store AND p.name = x.product
  JOIN pos_modifier_groups g ON g.store_id = v_store AND g.name = x.grp;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows <> 70 THEN
    RAISE EXCEPTION 'demo-suncity: % of 70 pizza questions attached', v_rows;
  END IF;

  -- ── The expanded recipes ────────────────────────────────────────────────
  -- 045 already ran this boot, before this store existed: `recomputeFlat`'s
  -- SQL for this store only (048 does the same).
  DELETE FROM pos_product_components_flat WHERE store_id = v_store;
  INSERT INTO pos_product_components_flat (store_id, variant_id, leaf_variant_id, quantity_per_unit)
  WITH RECURSIVE walk AS (
    SELECT pc.store_id, pc.variant_id AS root_id, pc.component_variant_id AS node_id,
           pc.quantity::bigint AS qty, 1 AS depth
    FROM pos_product_components pc
    WHERE pc.store_id = v_store
    UNION ALL
    SELECT w.store_id, w.root_id, pc.component_variant_id, w.qty * pc.quantity, w.depth + 1
    FROM walk w
    JOIN pos_variants nv ON nv.id = w.node_id
    JOIN pos_products np ON np.id = nv.product_id
    JOIN pos_product_components pc ON pc.variant_id = w.node_id AND pc.store_id = w.store_id
    WHERE np.kind = 'composite' AND np.stock_mode = 'derived' AND w.depth < 8
  )
  SELECT w.store_id, w.root_id, w.node_id, SUM(w.qty)::int
  FROM walk w
  JOIN pos_variants lv ON lv.id = w.node_id
  JOIN pos_products lp ON lp.id = lv.product_id
  WHERE NOT (lp.kind = 'composite' AND lp.stock_mode = 'derived')
  GROUP BY w.store_id, w.root_id, w.node_id;

  -- ── The guest's menu ────────────────────────────────────────────────────
  -- Published at /m/demo-suncity-menu with the place's own header. Only while
  -- empty, like 056/059: whatever the owner (or a visitor with the demo's
  -- credentials) set afterwards stays. No guest ordering — there are no tables.
  UPDATE pos_stores
     SET public_menu_token = 'demo-suncity-menu', public_menu_enabled = TRUE
   WHERE id = v_store AND public_menu_token IS NULL;

  UPDATE pos_stores
     SET public_logo_url = '/demo-suncity/logo.png',
         public_address = 'вул. 10 ОГШБ 52а, м. Малин',
         public_phone = '+380684868060',
         public_hours = '{"1":{"open":"11:00","close":"22:30"},"2":{"open":"11:00","close":"22:30"},"3":{"open":"11:00","close":"22:30"},"4":{"open":"11:00","close":"22:30"},"5":{"open":"11:00","close":"22:30"},"6":{"open":"11:00","close":"22:30"},"7":{"open":"11:00","close":"22:30"}}'::jsonb
   WHERE id = v_store
     AND public_logo_url IS NULL AND public_address IS NULL
     AND public_phone IS NULL AND public_hours IS NULL;

  INSERT INTO pos_demo_seed (slug, version) VALUES ('demo-suncity', v_version)
  ON CONFLICT (slug) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();

  RAISE NOTICE 'demo-suncity store ready at version % (id %)', v_version, v_store;
END $$;
