// The Live Shop — Copyright (c) 2026 Serhii Merenkov / Technologies LLC
// Licensed under the OwnNet Source License 1.1 (source-available). See LICENSE.
// Commercial use requires a separate agreement: mer.sergei@gmail.com

// GENERATED by scripts/gen-icons.mjs from design/icons/ — edit the SVGs there, not this file.
// Colour glyphs (24 px grid) carry their own hue; UI glyphs (20 px grid) draw in currentColor.
// Render them at their grid size or twice it — anything else lands edges between pixels.
import { useId, type SVGProps } from 'react';

export type GlyphProps = Omit<SVGProps<SVGSVGElement>, 'ref'> & { size?: number };
export type Glyph = (props: GlyphProps) => JSX.Element;

/** Masks need an id unique in the document; useId is stable across SSR and hydration. */
const useGlyphId = () => useId().replace(/:/g, '') + '-';

/** Colour glyph, 24 px grid · green. */
export function BarChart3({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="3" y="13" width="4" height="8" rx="1.5" fill="#43AE59" fillOpacity=".45"/><rect x="10" y="8" width="4" height="13" rx="1.5" fill="#43AE59" fillOpacity=".7"/><rect x="17" y="3" width="4" height="18" rx="1.5" fill="#43AE59"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · violet. */
export function Bot({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M12 7V4.5" fill="none" stroke="#8A6CEF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><circle cx="12" cy="3.5" r="1.5" fill="#8A6CEF"/><rect x="4" y="7" width="16" height="13" rx="4" fill="#8A6CEF"/><g fill="#8A6CEF" fillOpacity=".6"><rect x="1" y="11" width="2" height="5" rx="1"/><rect x="21" y="11" width="2" height="5" rx="1"/></g><g fill="#FFFFFF"><circle cx="9" cy="12.5" r="1.75"/><circle cx="15" cy="12.5" r="1.75"/><rect x="10" y="16" width="4" height="1" rx=".5" fillOpacity=".7"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function Building2({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="4" y="3" width="11" height="18" rx="2" fill="#6C7D93"/><rect x="16" y="9" width="5" height="12" rx="1.5" fill="#6C7D93" fillOpacity=".55"/><g fill="#FFFFFF" fillOpacity=".6"><rect x="6" y="6" width="2" height="2"/><rect x="11" y="6" width="2" height="2"/><rect x="6" y="10" width="2" height="2"/><rect x="11" y="10" width="2" height="2"/><rect x="6" y="14" width="2" height="2"/><rect x="11" y="14" width="2" height="2"/><rect x="8" y="17" width="3" height="4"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · red. */
export function CalendarClock({ size = 24, ...props }: GlyphProps) {
  const u = useGlyphId();
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <mask id={u + 'cut'} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect x="0" y="0" width="24" height="24" fill="#FFFFFF"/><circle cx="17" cy="17" r="6.5" fill="#000000"/></mask><g mask={'url(#' + u + 'cut)'}><rect x="3" y="5" width="18" height="16" rx="3" fill="#F4386A" fillOpacity=".2" stroke="#F4386A" strokeWidth="2"/><path d="M3 8a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v2H3Z" fill="#F4386A"/><path d="M6 13h2v2H6zM10 13h2v2h-2zM6 16h2v2H6z" fill="#F4386A"/></g><path d="M8 3V6M16 3V6" fill="none" stroke="#F4386A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><circle cx="17" cy="17" r="4.5" fill="#F4386A" fillOpacity=".2" stroke="#F4386A" strokeWidth="2"/><path d="M17 15V17H18.5" fill="none" stroke="#F4386A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · orange. */
export function ChefHat({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <g fill="#F4891F"><circle cx="8" cy="9.5" r="4"/><circle cx="16" cy="9.5" r="4"/><circle cx="12" cy="7.5" r="5"/><rect x="7" y="10" width="10" height="7"/><rect x="7" y="18" width="10" height="3" rx="1"/></g><path d="M10 13v2.5M14 13v2.5" fill="none" stroke="#FFFFFF" strokeOpacity=".55" strokeWidth="2" strokeLinecap="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · teal. */
export function ClipboardCheck({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="4" y="5" width="16" height="16" rx="3" fill="#2E9F91" fillOpacity=".22" stroke="#2E9F91" strokeWidth="2"/><rect x="8" y="2" width="8" height="5" rx="1.5" fill="#2E9F91"/><path d="M8.5 13.5 11 16 15.5 11" fill="none" stroke="#2E9F91" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · orange. */
export function Coffee({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M8 3.5V6M12 3.5V6" fill="none" stroke="#F4891F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeOpacity=".5"/><path d="M4 9H17V14A5 5 0 0 1 12 19H9A5 5 0 0 1 4 14Z" fill="#F4891F"/><path d="M17 11h1.5a2.5 2.5 0 0 1 0 5H16.5" fill="none" stroke="#F4891F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><rect x="3" y="20" width="15" height="2" rx="1" fill="#F4891F" fillOpacity=".5"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · yellow. */
export function Coins({ size = 24, ...props }: GlyphProps) {
  const u = useGlyphId();
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <mask id={u + 'cut'} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect x="0" y="0" width="24" height="24" fill="#FFFFFF"/><circle cx="9" cy="15" r="7.5" fill="#000000"/></mask><circle cx="15" cy="9" r="6" fill="#F8C00F" fillOpacity=".55" mask={'url(#' + u + 'cut)'}/><circle cx="9" cy="15" r="6" fill="#F8C00F"/><circle cx="9" cy="15" r="3.5" fill="none" stroke="#FFFFFF" strokeOpacity=".6" strokeWidth="2"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function Download({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M4 14v3.5A3.5 3.5 0 0 0 7.5 21h9a3.5 3.5 0 0 0 3.5-3.5V14" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M12 3v11M7.5 9.5 12 14l4.5-4.5" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · pink. */
export function Flower2({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M12 14V21" fill="none" stroke="#EE5B93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M13 18.5C13 16.5 14.5 15 17 15 17 17 15.5 18.5 13 18.5Z" fill="#EE5B93" fillOpacity=".6"/><g fill="#EE5B93"><circle cx="12" cy="5.25" r="3.25"/><circle cx="15.5" cy="7.75" r="3.25"/><circle cx="14.25" cy="12" r="3.25"/><circle cx="9.75" cy="12" r="3.25"/><circle cx="8.5" cy="7.75" r="3.25"/></g><circle cx="12" cy="9" r="2" fill="#FFFFFF" fillOpacity=".75"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · orange. */
export function Grid3X3({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="6" y="6" width="12" height="12" rx="3" fill="#F4891F"/><g fill="#F4891F" fillOpacity=".5"><rect x="9" y="2" width="6" height="2" rx="1"/><rect x="9" y="20" width="6" height="2" rx="1"/><rect x="2" y="9" width="2" height="6" rx="1"/><rect x="20" y="9" width="2" height="6" rx="1"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · khaki. */
export function KeyRound({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path fillRule="evenodd" d="M7 7a5 5 0 1 1 0 10A5 5 0 0 1 7 7Zm0 3.25a1.75 1.75 0 1 0 0 3.5 1.75 1.75 0 0 0 0-3.5Z" fill="#C0A96B"/><g fill="#C0A96B"><rect x="11" y="11" width="10" height="2"/><rect x="16" y="13" width="2" height="3"/><rect x="19" y="13" width="2" height="4"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · gray. */
export function Laptop({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="5" y="5" width="14" height="9" rx="2" fill="#8E9196" fillOpacity=".22" stroke="#8E9196" strokeWidth="2"/><rect x="2" y="16" width="20" height="3" rx="1.5" fill="#8E9196"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · gray. */
export function Lock({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M8 10V7.5a4 4 0 0 1 8 0V10" fill="none" stroke="#8E9196" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><rect x="4" y="10" width="16" height="11" rx="3" fill="#8E9196"/><rect x="11" y="14" width="2" height="4" rx="1" fill="#FFFFFF" fillOpacity=".85"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function MessageCircle({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M12 4c5 0 9 3.25 9 7.5S17 19 12 19c-1 0-2-.25-2.75-.5L5 20.5l1.25-3.5C4.25 15.5 3 13.5 3 11.5 3 7.25 7 4 12 4Z" fill="#1B9DF0" fillOpacity=".22" stroke="#1B9DF0" strokeWidth="2" strokeLinejoin="round"/><g fill="#1B9DF0"><circle cx="8.5" cy="11.5" r="1.25"/><circle cx="12" cy="11.5" r="1.25"/><circle cx="15.5" cy="11.5" r="1.25"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function Monitor({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="3" y="4" width="18" height="12" rx="2.5" fill="#6C7D93" fillOpacity=".22" stroke="#6C7D93" strokeWidth="2"/><path d="M12 16v4M8 20h8" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · khaki. */
export function Package({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M5 3H19L21 7H3Z" fill="#C0A96B" fillOpacity=".6"/><rect x="3" y="7" width="18" height="14" rx="2.5" fill="#C0A96B"/><path d="M10 3h4v8h-4z" fill="#FFFFFF" fillOpacity=".6"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function QrCode({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="3" y="3" width="7" height="7" rx="2" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><rect x="14" y="3" width="7" height="7" rx="2" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><rect x="3" y="14" width="7" height="7" rx="2" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><g fill="#6C7D93"><rect x="5" y="5" width="3" height="3" rx=".5"/><rect x="16" y="5" width="3" height="3" rx=".5"/><rect x="5" y="16" width="3" height="3" rx=".5"/><rect x="14" y="14" width="3" height="3" rx=".5"/><rect x="18" y="18" width="3" height="3" rx=".5"/></g><g fill="#6C7D93" fillOpacity=".45"><rect x="18" y="14" width="3" height="3" rx=".5"/><rect x="14" y="18" width="3" height="3" rx=".5"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function Receipt({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M5 20.5V6a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v14.5L17.25 19 15.5 20.5 13.75 19 12 20.5 10.25 19 8.5 20.5 6.75 19Z" fill="#1B9DF0" fillOpacity=".22" stroke="#1B9DF0" strokeWidth="2" strokeLinejoin="round"/><path d="M9 9H15M9 13H13" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function ScanLine({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M3 8V6a3 3 0 0 1 3-3h2M16 3h2a3 3 0 0 1 3 3v2M21 16v2a3 3 0 0 1-3 3h-2M8 21H6a3 3 0 0 1-3-3v-2" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M6 7h2v10H6zM9 7h1v10H9zM11 7h2v10h-2zM14 7h1v10h-1zM16 7h2v10h-2z" fill="#1B9DF0"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · gray. */
export function Settings({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <circle cx="12" cy="12" r="5.5" fill="none" stroke="#8E9196" strokeWidth="4"/><g fill="#8E9196"><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(0 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(45 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(90 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(135 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(180 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(225 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(270 12 12)"/><rect x="10" y="2" width="4" height="5" rx="1" transform="rotate(315 12 12)"/></g>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function ShieldCheck({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M12 3 19 5.5V11.25C19 15.75 16 19.25 12 21 8 19.25 5 15.75 5 11.25V5.5Z" fill="#6C7D93" stroke="#6C7D93" strokeWidth="2" strokeLinejoin="round"/><path d="M8.5 12 11 14.5 15.5 9.5" fill="none" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function Shirt({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M8 3.5C8.5 5 10 6 12 6S15.5 5 16 3.5L21 6.5 19 10.5 17 9.75V20a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V9.75L5 10.5 3 6.5Z" fill="#1B9DF0"/><path d="M9.5 4.5C10 5.5 11 6 12 6S14 5.5 14.5 4.5" fill="none" stroke="#FFFFFF" strokeOpacity=".6" strokeWidth="1" strokeLinecap="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · blue. */
export function ShoppingCart({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M7 9V8a5 5 0 0 1 10 0v1" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M5 12 6.25 19.25A1 1 0 0 0 7.25 20H16.75A1 1 0 0 0 17.75 19.25L19 12Z" fill="#1B9DF0" fillOpacity=".22" stroke="#1B9DF0" strokeWidth="2" strokeLinejoin="round"/><rect x="2" y="9" width="20" height="3" rx="1.5" fill="#1B9DF0"/><path d="M10 14.5V17M14 14.5V17" fill="none" stroke="#1B9DF0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · yellow. */
export function Sparkles({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M10 3C10.75 7.25 12.75 9.25 17 10 12.75 10.75 10.75 12.75 10 17 9.25 12.75 7.25 10.75 3 10 7.25 9.25 9.25 7.25 10 3Z" fill="#F8C00F"/><path d="M18 13.5C18.25 15.75 19.25 16.75 21.5 17 19.25 17.25 18.25 18.25 18 20.5 17.75 18.25 16.75 17.25 14.5 17 16.75 16.75 17.75 15.75 18 13.5Z" fill="#F8C00F" fillOpacity=".7"/><circle cx="18.5" cy="5.5" r="1.5" fill="#F8C00F" fillOpacity=".5"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · yellow. */
export function Star({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M12 3.5 14.5 9 20.5 9.5 16.5 14 17.5 20 12 17 6.5 20 7.5 14 3.5 9.5 9.5 9Z" fill="#F8C00F" stroke="#F8C00F" strokeWidth="2" strokeLinejoin="round"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · red. */
export function Store({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M5 12.5V20a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-7.5" fill="#F4386A" fillOpacity=".22" stroke="#F4386A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><rect x="10" y="15" width="4" height="6" rx="1" fill="#F4386A"/><path d="M3 8.5 4.75 4h14.5L21 8.5v1a2.25 2.25 0 0 1-4.5 0 2.25 2.25 0 0 1-4.5 0 2.25 2.25 0 0 1-4.5 0 2.25 2.25 0 0 1-4.5 0Z" fill="#F4386A"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · violet. */
export function Tag({ size = 24, ...props }: GlyphProps) {
  const u = useGlyphId();
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <mask id={u + 'cut'} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect x="0" y="0" width="24" height="24" fill="#FFFFFF"/><circle cx="9.5" cy="12" r="1.75" fill="#000000"/></mask><path d="M9.5 6H18a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3H9.5L3.5 12Z" fill="#8A6CEF" stroke="#8A6CEF" strokeWidth="2" strokeLinejoin="round" mask={'url(#' + u + 'cut)'}/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · gray. */
export function Terminal({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="3" y="4" width="18" height="16" rx="3" fill="#8E9196"/><path d="M7 9.5 9.5 12 7 14.5" fill="none" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M12 15h5" fill="none" stroke="#FFFFFF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeOpacity=".7"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · violet. */
export function Users({ size = 24, ...props }: GlyphProps) {
  const u = useGlyphId();
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <mask id={u + 'cut'} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect x="0" y="0" width="24" height="24" fill="#FFFFFF"/><circle cx="9" cy="8" r="4" fill="#000000" stroke="#000000" strokeWidth="3"/><path d="M2 19.5C2 16 5 14 9 14s7 2 7 5.5V21H2Z" fill="#000000" stroke="#000000" strokeWidth="3"/></mask><g mask={'url(#' + u + 'cut)'} fill="#8A6CEF" fillOpacity=".5"><circle cx="16.5" cy="7.5" r="3"/><path d="M12 13.5C13.25 12.75 14.75 12.5 16.5 12.5 19.5 12.5 22 14 22 17V18a1 1 0 0 1-1 1H12Z"/></g><circle cx="9" cy="8" r="4" fill="#8A6CEF"/><path d="M2 19.5C2 16 5 14 9 14s7 2 7 5.5V20a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1Z" fill="#8A6CEF"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function UtensilsCrossed({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M5 3v4.5a2 2 0 0 0 4 0V3M7 3v4M7 9.5V21" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M18 3C15.25 4.25 14 7.75 14 12.5H18Z" fill="#6C7D93"/><rect x="16" y="12" width="2" height="9" rx="1" fill="#6C7D93"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · live. */
export function Video({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <circle cx="12" cy="12" r="3" fill="#FF3D7A"/><path d="M7.75 7.75A6 6 0 0 0 7.75 16.25M16.25 7.75A6 6 0 0 1 16.25 16.25" fill="none" stroke="#FF3D7A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M5.5 5.5A9.25 9.25 0 0 0 5.5 18.5M18.5 5.5A9.25 9.25 0 0 1 18.5 18.5" fill="none" stroke="#FF3D7A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeOpacity=".5"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · teal. */
export function Warehouse({ size = 24, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <rect x="7" y="3" width="10" height="8" rx="1.5" fill="#2E9F91"/><rect x="2" y="13" width="9" height="8" rx="1.5" fill="#2E9F91"/><rect x="13" y="13" width="9" height="8" rx="1.5" fill="#2E9F91"/><path d="M11 3h2v3h-2zM5 13h3v3H5zM16 13h3v3h-3z" fill="#FFFFFF" fillOpacity=".6"/>
    </svg>
  );
}

/** Colour glyph, 24 px grid · slate. */
export function WifiOff({ size = 24, ...props }: GlyphProps) {
  const u = useGlyphId();
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false" {...props}>
      <mask id={u + 'cut'} maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24"><rect x="0" y="0" width="24" height="24" fill="#FFFFFF"/><path d="M4 4 20 20" stroke="#000000" strokeWidth="5" strokeLinecap="round"/></mask><g mask={'url(#' + u + 'cut)'}><path d="M5.25 11.25a9.5 9.5 0 0 1 13.5 0M8.5 14.5a5 5 0 0 1 7 0" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><circle cx="12" cy="18.5" r="1.75" fill="#6C7D93"/></g><path d="M4 4 20 20" fill="none" stroke="#6C7D93" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function ArrowRight({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M4 10H16M11 5 16 10 11 15" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function Check({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M4 10.5 8 14.5 16 5.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function ChevronDown({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M4.5 8 10 13.5 15.5 8" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function ChevronRight({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M8 4.5 13.5 10 8 15.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function MoreHorizontal({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <g fill="currentColor"><circle cx="4" cy="10" r="1.75"/><circle cx="10" cy="10" r="1.75"/><circle cx="16" cy="10" r="1.75"/></g>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function Pencil({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M13 3.5 16.5 7 7 16.5H3.5V13ZM11 5.5 14.5 9" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function Plus({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M10 4V16M4 10H16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function Search({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <circle cx="8.5" cy="8.5" r="5.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M12.5 12.5 16.5 16.5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function Trash2({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M3 5H17M8 5V4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v1M5 5l.75 11a1 1 0 0 0 1 1h6.5a1 1 0 0 0 1-1L15 5M8 8.5v5M12 8.5v5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** UI glyph, 20 px grid. */
export function X({ size = 20, ...props }: GlyphProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path d="M5 5 15 15M15 5 5 15" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

/** Every colour glyph by name. */
export const COLOR_GLYPHS = { BarChart3, Bot, Building2, CalendarClock, ChefHat, ClipboardCheck, Coffee, Coins, Download, Flower2, Grid3X3, KeyRound, Laptop, Lock, MessageCircle, Monitor, Package, QrCode, Receipt, ScanLine, Settings, ShieldCheck, Shirt, ShoppingCart, Sparkles, Star, Store, Tag, Terminal, Users, UtensilsCrossed, Video, Warehouse, WifiOff } as const satisfies Record<string, Glyph>;

/** Every UI glyph by name. */
export const UI_GLYPHS = { ArrowRight, Check, ChevronDown, ChevronRight, MoreHorizontal, Pencil, Plus, Search, Trash2, X } as const satisfies Record<string, Glyph>;
